TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "后退",
    "forward_button": "前进",
    "exit_button": "退出",
    "search_hint": "搜索...",
    "show_hidden_checkbox": "显示隐藏项",
    "name_column": "名称",
    "type_column": "类型",
    "size_column": "大小",
    "preview_select_file": "请选择要预览的文件。",
    "folder_selected": "已选择文件夹:\n{path}",
    "no_preview_available": "此项目没有可用预览。",
    "unable_preview_pdf": "无法预览 PDF。\n{exc}",
    "unable_preview_file": "无法预览文件。\n{exc}",
    "empty_file": "该文件为空。",
    "preview_truncated_suffix": "\n\n... 预览已截断 ...",
    "context_open": "打开",
    "context_rename": "重命名",
    "context_delete": "删除",
    "scan": "扫描",
    "scan_dialog_title": "扫描文档",
    "scan_scanner_label": "扫描仪",
    "scan_default_scanner": "默认扫描仪",
    "scan_source_label": "来源",
    "scan_source_flatbed": "平板",
    "scan_source_adf_simplex": "ADF（单面）",
    "scan_source_adf_duplex": "ADF（双面）",
    "scan_color_mode_label": "颜色模式",
    "scan_color_mode_color": "彩色",
    "scan_color_mode_grayscale": "灰度",
    "scan_color_mode_black_white": "黑白",
    "scan_dpi_label": "分辨率 (DPI)",
    "scan_page_size_label": "页面大小",
    "scan_page_size_auto": "自动",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "输出类型",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "扫描多页",
    "scan_output_file_label": "输出文件",
    "scan_browse_button": "浏览...",
    "scan_open_after_label": "扫描后打开",
    "scan_select_output_file_title": "选择输出文件",
    "scan_button": "扫描",
    "scan_cancel_button": "取消",
    "scan_output_file_required": "请选择输出文件。",
    "scan_output_folder_not_exists": "输出文件夹不存在。",
    "scan_not_available_message": "扫描表单已配置。此版本暂不支持扫描仪集成。",
    "this_pc_root": "此电脑",
    "tree_expand_placeholder": "...",
    "page_label": "第 {page_no}/{page_count} 页",
    "showing_first_pages": "正在显示前 {shown_pages} 页，共 {page_count} 页...",
    "page_move_error_title": "PDF 页面移动",
    "unable_move_pdf_page": "无法移动 PDF 页面。\n{exc}",
    "drop_overlay_label": "拖放到第 {page_index} 页",
    "preview_edit_button": "打开",
    "preview_save_button": "保存",
    "preview_cancel_button": "取消",
    "preview_save_as_button": "另存为",
    "preview_delete_button": "删除文件",
    "preview_zoom_in_button": "放大",
    "preview_zoom_out_button": "缩小",
    "preview_show_mode": "显示模式",
    "preview_show_1_page_wide": "按宽度显示 1 页",
    "preview_show_2_pages_wide": "按宽度显示 2 页",
    "preview_show_1_page_tall": "按高度显示 1 页",
    "preview_show_manual_scale": "手动缩放",
    "preview_rotate_button": "旋转",
    "preview_rotate_all_left_button": "全部向左旋转",
    "preview_rotate_left_button": "向左旋转",
    "preview_rotate_right_button": "向右旋转",
    "preview_rotate_all_right_button": "全部向右旋转",
    "preview_auto_rotate_button": "Auto rotate",
    "preview_optimize_button": "优化",
    "preview_adjust_page_width_button": "调整页面宽度",
    "preview_remove_page_button": "删除页面",
    "preview_move_page_button": "移动页面",
    "preview_import_button": "导入",
    "preview_import_from_file_button": "从文件导入",
    "preview_import_from_scanner_button": "从扫描仪导入",
    "preview_export_pages_button": "导出页面",
    "import_pdf_dialog_title": "从文件导入PDF",
    "import_pdf_source_label": "源文件名",
    "import_pdf_browse_button": "浏览...",
    "import_pdf_file_dialog_title": "选择PDF文件",
    "import_pdf_destination_label": "目标位置",
    "import_pdf_after_page": "在页面之后",
    "import_pdf_source_required": "请选择要导入的PDF文件。",
    "export_pdf_pages_dialog_title": "导出页面",
    "export_pdf_page_numbers_label": "页码",
    "export_pdf_file_name_label": "文件名",
    "export_pdf_file_name_required": "请输入导出文件名。",
    "export_pdf_page_numbers_invalid": "请输入类似 1,3-5 的页码。",
    "export_pdf_save_dialog_title": "保存导出的页面",
    "move_page_dialog_title": "移动 PDF 页面",
    "move_page_source_label": "要移动的页面:",
    "move_page_destination_label": "目标位置:",
    "move_page_destination_page_label": "页码:",
    "move_page_at_begin": "到开头",
    "move_page_before": "在该页码之前",
    "move_page_after": "在该页码之后",
    "move_page_at_end": "到末尾",
    "select_pdf_page": "请先选择页面。",
    "confirm_remove_page": "删除第 {page_no} 页吗?",
    "confirm_save_selected_file": "保存所选文件的更改吗?",
    "confirm_save_before_exit": "有 {count} 个 PDF 文件包含未保存更改。退出前是否保存?",
    "confirm_delete": "删除 {path} 吗?",
    "insert_before": "在前面插入",
    "insert_after": "在后面插入",
    "undo_no_action": "没有可撤销的操作",
    "undo_done": "撤销成功",
    "undo_title": "撤销",
    "file_type_folder": "文件夹",
    "file_type_file": "文件",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "优化所有 PDF",
    "tree_adjust_page_width_all_pdf": "调整所有页面宽度",
    "tree_no_folder_selected": "请先在树中选择文件夹。",
    "tree_no_folder_or_pdf_selected": "请先在树中选择文件夹或 PDF 文件。",
    "tree_optimize_all_done": "已优化: {optimized_count}\n失败: {failed_count}",
    "tree_adjust_page_width_all_done": "已调整: {adjusted_count}\n失败: {failed_count}",
}
