TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "뒤로",
    "forward_button": "앞으로",
    "exit_button": "종료",
    "search_hint": "검색...",
    "show_hidden_checkbox": "숨김 파일 표시",
    "name_column": "이름",
    "type_column": "유형",
    "size_column": "크기",
    "preview_select_file": "미리 볼 파일을 선택하세요.",
    "folder_selected": "선택한 폴더:\n{path}",
    "no_preview_available": "이 항목은 미리보기를 지원하지 않습니다.",
    "unable_preview_pdf": "PDF 미리보기를 할 수 없습니다.\n{exc}",
    "unable_preview_file": "파일 미리보기를 할 수 없습니다.\n{exc}",
    "empty_file": "이 파일은 비어 있습니다.",
    "preview_truncated_suffix": "\n\n... 미리보기가 잘렸습니다 ...",
    "context_open": "열기",
    "context_rename": "이름 바꾸기",
    "context_delete": "삭제",
    "scan": "스캔",
    "this_pc_root": "내 PC",
    "tree_expand_placeholder": "...",
    "page_label": "페이지 {page_no}/{page_count}",
    "showing_first_pages": "총 {page_count}페이지 중 처음 {shown_pages}페이지를 표시합니다...",
    "page_move_error_title": "PDF 페이지 이동",
    "unable_move_pdf_page": "PDF 페이지를 이동할 수 없습니다.\n{exc}",
    "drop_overlay_label": "페이지 {page_index}에 놓기",
    "preview_edit_button": "열기",
    "preview_save_button": "저장",
    "preview_cancel_button": "취소",
    "preview_save_as_button": "다른 이름으로 저장",
    "preview_delete_button": "파일 삭제",
    "preview_zoom_in_button": "확대",
    "preview_zoom_out_button": "축소",
    "preview_show_mode": "보기 모드",
    "preview_show_1_page_wide": "가로 1페이지 보기",
    "preview_show_2_pages_wide": "가로 2페이지 보기",
    "preview_show_1_page_tall": "세로 1페이지 보기",
    "preview_show_manual_scale": "수동 배율",
    "preview_rotate_button": "회전",
    "preview_rotate_all_left_button": "전체 왼쪽 회전",
    "preview_rotate_left_button": "왼쪽 회전",
    "preview_rotate_right_button": "오른쪽 회전",
    "preview_rotate_all_right_button": "전체 오른쪽 회전",
    "preview_auto_rotate_button": "Auto rotate",
    "preview_optimize_button": "최적화",
    "preview_adjust_page_width_button": "페이지 너비 맞춤",
    "preview_remove_page_button": "페이지 제거",
    "preview_move_page_button": "페이지 이동",
    "preview_import_from_file_button": "파일에서 가져오기",
    "preview_export_pages_button": "페이지 내보내기",
    "import_pdf_dialog_title": "파일에서 PDF 가져오기",
    "import_pdf_source_label": "원본 파일 이름",
    "import_pdf_browse_button": "찾아보기...",
    "import_pdf_file_dialog_title": "PDF 파일 선택",
    "import_pdf_destination_label": "대상 위치",
    "import_pdf_after_page": "페이지 뒤에",
    "import_pdf_source_required": "가져올 PDF 파일을 선택하세요.",
    "export_pdf_pages_dialog_title": "페이지 내보내기",
    "export_pdf_page_numbers_label": "페이지 번호",
    "export_pdf_file_name_label": "파일 이름",
    "export_pdf_file_name_required": "내보낼 파일 이름을 입력하세요.",
    "export_pdf_page_numbers_invalid": "1,3-5와 같은 페이지 번호를 입력하세요.",
    "export_pdf_save_dialog_title": "내보낸 페이지 저장",
    "move_page_dialog_title": "PDF 페이지 이동",
    "move_page_source_label": "이동할 페이지:",
    "move_page_destination_label": "대상 위치:",
    "move_page_destination_page_label": "페이지 번호:",
    "move_page_at_begin": "맨 앞",
    "move_page_before": "번호 앞",
    "move_page_after": "번호 뒤",
    "move_page_at_end": "맨 끝",
    "select_pdf_page": "먼저 페이지를 선택하세요.",
    "confirm_remove_page": "페이지 {page_no}을(를) 제거할까요?",
    "confirm_save_selected_file": "선택한 파일의 변경 내용을 저장할까요?",
    "confirm_save_before_exit": "{count}개의 PDF 파일에 저장되지 않은 변경 사항이 있습니다. 종료 전에 저장할까요?",
    "confirm_delete": "{path}을(를) 삭제할까요?",
    "insert_before": "앞에 삽입",
    "insert_after": "뒤에 삽입",
    "undo_no_action": "실행 취소할 작업이 없습니다",
    "undo_done": "실행 취소 완료",
    "undo_title": "실행 취소",
    "file_type_folder": "폴더",
    "file_type_file": "파일",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "모든 PDF 최적화",
    "tree_adjust_page_width_all_pdf": "모든 페이지 너비 맞춤",
    "tree_no_folder_selected": "먼저 트리에서 폴더를 선택하세요.",
    "tree_no_folder_or_pdf_selected": "먼저 트리에서 폴더 또는 PDF 파일을 선택하세요.",
    "tree_optimize_all_done": "최적화됨: {optimized_count}\n실패: {failed_count}",
    "tree_adjust_page_width_all_done": "맞춤 완료: {adjusted_count}\n실패: {failed_count}",
}
