TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "Voltar",
    "forward_button": "Avancar",
    "exit_button": "Sair",
    "search_hint": "Pesquisar...",
    "show_hidden_checkbox": "Mostrar ocultos",
    "name_column": "Nome",
    "type_column": "Tipo",
    "size_column": "Tamanho",
    "preview_select_file": "Selecione um arquivo para visualizar.",
    "folder_selected": "Pasta selecionada:\n{path}",
    "no_preview_available": "Nenhuma visualizacao disponivel para este item.",
    "unable_preview_pdf": "Nao foi possivel visualizar o PDF.\n{exc}",
    "unable_preview_file": "Nao foi possivel visualizar o arquivo.\n{exc}",
    "empty_file": "Este arquivo esta vazio.",
    "preview_truncated_suffix": "\n\n... visualizacao truncada ...",
    "context_open": "Abrir",
    "context_rename": "Renomear",
    "context_delete": "Excluir",
    "scan": "Escanear",
    "scan_dialog_title": "Digitalizar documentos",
    "scan_scanner_label": "Scanner",
    "scan_default_scanner": "Scanner padrão",
    "scan_source_label": "Origem",
    "scan_source_flatbed": "Mesa plana",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Duplex)",
    "scan_color_mode_label": "Modo de cor",
    "scan_color_mode_color": "Colorido",
    "scan_color_mode_grayscale": "Escala de cinza",
    "scan_color_mode_black_white": "Preto e branco",
    "scan_dpi_label": "Resolução (DPI)",
    "scan_page_size_label": "Tamanho da página",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Tipo de saída",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Digitalizar várias páginas",
    "scan_output_file_label": "Arquivo de saída",
    "scan_browse_button": "Procurar...",
    "scan_open_after_label": "Abrir após digitalizar",
    "scan_select_output_file_title": "Selecionar arquivo de saída",
    "scan_button": "Digitalizar",
    "scan_cancel_button": "Cancelar",
    "scan_output_file_required": "Selecione um arquivo de saída.",
    "scan_output_folder_not_exists": "A pasta de saída não existe.",
    "scan_not_available_message": "O formulário de digitalização está configurado. A integração com scanner ainda não está disponível nesta versão.",
    "this_pc_root": "Este Computador",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrando as primeiras {shown_pages} paginas de {page_count}...",
    "page_move_error_title": "Mover pagina PDF",
    "unable_move_pdf_page": "Nao foi possivel mover a pagina PDF.\n{exc}",
    "drop_overlay_label": "Soltar na pagina {page_index}",
    "preview_edit_button": "Abrir",
    "preview_save_button": "Salvar",
    "preview_cancel_button": "Cancelar",
    "preview_save_as_button": "Salvar como",
    "preview_delete_button": "Excluir arquivo",
    "preview_zoom_in_button": "Aumentar zoom",
    "preview_zoom_out_button": "Diminuir zoom",
    "preview_show_mode": "Modo de exibicao",
    "preview_show_1_page_wide": "Mostrar 1 pagina na largura",
    "preview_show_2_pages_wide": "Mostrar 2 paginas na largura",
    "preview_show_1_page_tall": "Mostrar 1 pagina na altura",
    "preview_show_manual_scale": "Escala manual",
    "preview_rotate_button": "Girar",
    "preview_rotate_all_left_button": "Girar tudo para a esquerda",
    "preview_rotate_left_button": "Girar para a esquerda",
    "preview_rotate_right_button": "Girar para a direita",
    "preview_rotate_all_right_button": "Girar tudo para a direita",
    "preview_auto_rotate_button": "Auto rotate",
    "preview_optimize_button": "Otimizar",
    "preview_adjust_page_width_button": "Ajustar largura da pagina",
    "preview_remove_page_button": "Remover pagina",
    "preview_move_page_button": "Mover pagina",
    "preview_import_from_file_button": "Importar do arquivo",
    "preview_export_pages_button": "Exportar páginas",
    "import_pdf_dialog_title": "Importar PDF do arquivo",
    "import_pdf_source_label": "Nome do arquivo de origem",
    "import_pdf_browse_button": "Procurar...",
    "import_pdf_file_dialog_title": "Selecionar arquivo PDF",
    "import_pdf_destination_label": "Destino",
    "import_pdf_after_page": "Depois da página",
    "import_pdf_source_required": "Selecione um arquivo PDF para importar.",
    "export_pdf_pages_dialog_title": "Exportar páginas",
    "export_pdf_page_numbers_label": "Números das páginas",
    "export_pdf_file_name_label": "Nome do arquivo",
    "export_pdf_file_name_required": "Informe um nome de arquivo para exportação.",
    "export_pdf_page_numbers_invalid": "Informe números de páginas como 1,3-5.",
    "export_pdf_save_dialog_title": "Salvar páginas exportadas",
    "move_page_dialog_title": "Mover pagina PDF",
    "move_page_source_label": "Pagina a mover:",
    "move_page_destination_label": "Destino:",
    "move_page_destination_page_label": "Numero da pagina:",
    "move_page_at_begin": "No inicio",
    "move_page_before": "Antes do numero",
    "move_page_after": "Depois do numero",
    "move_page_at_end": "No fim",
    "select_pdf_page": "Selecione uma pagina primeiro.",
    "confirm_remove_page": "Remover a pagina {page_no}?",
    "confirm_save_selected_file": "Salvar alteracoes no arquivo selecionado?",
    "confirm_save_before_exit": "Ha alteracoes nao salvas em {count} arquivo(s) PDF. Salvar antes de sair?",
    "confirm_delete": "Excluir {path}?",
    "insert_before": "Inserir antes",
    "insert_after": "Inserir depois",
    "undo_no_action": "Nada para desfazer",
    "undo_done": "Desfazer concluido",
    "undo_title": "Desfazer",
    "file_type_folder": "Pasta",
    "file_type_file": "Arquivo",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Otimizar todos os PDFs",
    "tree_adjust_page_width_all_pdf": "Ajustar largura da pagina para todos",
    "tree_no_folder_selected": "Selecione primeiro uma pasta na arvore.",
    "tree_no_folder_or_pdf_selected": "Selecione primeiro uma pasta ou um arquivo PDF na arvore.",
    "tree_optimize_all_done": "Otimizados: {optimized_count}\nFalhas: {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustados: {adjusted_count}\nFalhas: {failed_count}",
}
