TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "Voltar",
    "forward_button": "Avancar",
    "exit_button": "Sair",
    "search_hint": "Pesquisar...",
    "show_hidden_checkbox": "Mostrar ocultos",
    "name_column": "Nome",
    "type_column": "Tipo",
    "size_column": "Tamanho",
    "preview_select_file": "Selecione um arquivo para visualizar.",
    "folder_selected": "Pasta selecionada:\n{path}",
    "no_preview_available": "Nenhuma visualizacao disponivel para este item.",
    "unable_preview_pdf": "Nao foi possivel visualizar o PDF.\n{exc}",
    "unable_preview_file": "Nao foi possivel visualizar o arquivo.\n{exc}",
    "empty_file": "Este arquivo esta vazio.",
    "preview_truncated_suffix": "\n\n... visualizacao truncada ...",
    "context_open": "Abrir",
    "context_rename": "Renomear",
    "context_delete": "Excluir",
    "this_pc_root": "Este Computador",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrando as primeiras {shown_pages} paginas de {page_count}...",
    "page_move_error_title": "Mover pagina PDF",
    "unable_move_pdf_page": "Nao foi possivel mover a pagina PDF.\n{exc}",
    "drop_overlay_label": "Soltar na pagina {page_index}",
    "preview_edit_button": "Abrir",
    "preview_save_button": "Salvar",
    "preview_delete_button": "Excluir arquivo",
    "preview_zoom_in_button": "Aumentar zoom",
    "preview_zoom_out_button": "Diminuir zoom",
    "preview_show_mode": "Modo de exibicao",
    "preview_show_1_page_wide": "Mostrar 1 pagina na largura",
    "preview_show_2_pages_wide": "Mostrar 2 paginas na largura",
    "preview_show_1_page_tall": "Mostrar 1 pagina na altura",
    "preview_rotate_button": "Girar",
    "preview_rotate_all_left_button": "Girar tudo para a esquerda",
    "preview_rotate_left_button": "Girar para a esquerda",
    "preview_rotate_right_button": "Girar para a direita",
    "preview_rotate_all_right_button": "Girar tudo para a direita",
    "preview_optimize_button": "Otimizar",
    "preview_adjust_page_width_button": "Ajustar largura da pagina",
    "preview_remove_page_button": "Remover pagina",
    "preview_move_page_button": "Mover pagina",
    "move_page_dialog_title": "Mover pagina PDF",
    "move_page_source_label": "Pagina a mover:",
    "move_page_destination_label": "Destino:",
    "move_page_destination_page_label": "Numero da pagina:",
    "move_page_at_begin": "No inicio",
    "move_page_before": "Antes do numero",
    "move_page_after": "Depois do numero",
    "move_page_at_end": "No fim",
    "select_pdf_page": "Selecione uma pagina primeiro.",
    "confirm_remove_page": "Remover a pagina {page_no}?",
    "confirm_save_selected_file": "Salvar alteracoes no arquivo selecionado?",
    "confirm_save_before_exit": "Ha alteracoes nao salvas em {count} arquivo(s) PDF. Salvar antes de sair?",
    "confirm_delete": "Excluir {path}?",
    "insert_before": "Inserir antes",
    "insert_after": "Inserir depois",
    "undo_no_action": "Nada para desfazer",
    "undo_done": "Desfazer concluido",
    "undo_title": "Desfazer",
    "file_type_folder": "Pasta",
    "file_type_file": "Arquivo",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Otimizar todos os PDFs",
    "tree_adjust_page_width_all_pdf": "Ajustar largura da pagina para todos",
    "tree_no_folder_selected": "Selecione primeiro uma pasta na arvore.",
    "tree_no_folder_or_pdf_selected": "Selecione primeiro uma pasta ou um arquivo PDF na arvore.",
    "tree_optimize_all_done": "Otimizados: {optimized_count}\nFalhas: {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustados: {adjusted_count}\nFalhas: {failed_count}",
}
