TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "Atras",
    "forward_button": "Adelante",
    "exit_button": "Salir",
    "search_hint": "Buscar...",
    "show_hidden_checkbox": "Mostrar ocultos",
    "name_column": "Nombre",
    "type_column": "Tipo",
    "size_column": "Tamano",
    "preview_select_file": "Seleccione un archivo para previsualizar.",
    "folder_selected": "Carpeta seleccionada:\n{path}",
    "no_preview_available": "No hay vista previa disponible para este elemento.",
    "unable_preview_pdf": "No se puede previsualizar el PDF.\n{exc}",
    "unable_preview_file": "No se puede previsualizar el archivo.\n{exc}",
    "empty_file": "Este archivo esta vacio.",
    "preview_truncated_suffix": "\n\n... vista previa recortada ...",
    "context_open": "Abrir",
    "context_rename": "Renombrar",
    "context_delete": "Eliminar",
    "scan": "Escanear",
    "scan_dialog_title": "Escanear documentos",
    "scan_scanner_label": "Escáner",
    "scan_default_scanner": "Escáner predeterminado",
    "scan_source_label": "Origen",
    "scan_source_flatbed": "Cama plana",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Dúplex)",
    "scan_color_mode_label": "Modo de color",
    "scan_color_mode_color": "Color",
    "scan_color_mode_grayscale": "Escala de grises",
    "scan_color_mode_black_white": "Blanco y negro",
    "scan_dpi_label": "Resolución (DPI)",
    "scan_page_size_label": "Tamaño de página",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Tipo de salida",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Escanear varias páginas",
    "scan_output_file_label": "Archivo de salida",
    "scan_browse_button": "Examinar...",
    "scan_open_after_label": "Abrir después de escanear",
    "scan_select_output_file_title": "Seleccionar archivo de salida",
    "scan_button": "Escanear",
    "scan_cancel_button": "Cancelar",
    "scan_output_file_required": "Seleccione un archivo de salida.",
    "scan_output_folder_not_exists": "La carpeta de salida no existe.",
    "scan_not_available_message": "El formulario de escaneo está configurado. La integración con el escáner aún no está disponible en esta versión.",
    "this_pc_root": "Este equipo",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrando las primeras {shown_pages} paginas de {page_count}...",
    "page_move_error_title": "Mover pagina PDF",
    "unable_move_pdf_page": "No se pudo mover la pagina PDF.\n{exc}",
    "drop_overlay_label": "Soltar en la pagina {page_index}",
    "preview_edit_button": "Abrir",
    "preview_save_button": "Guardar",
    "preview_cancel_button": "Cancelar",
    "preview_save_as_button": "Guardar como",
    "preview_delete_button": "Eliminar archivo",
    "preview_zoom_in_button": "Acercar",
    "preview_zoom_out_button": "Alejar",
    "preview_show_mode": "Modo de visualizacion",
    "preview_show_1_page_wide": "Mostrar 1 pagina de ancho",
    "preview_show_2_pages_wide": "Mostrar 2 paginas de ancho",
    "preview_show_1_page_tall": "Mostrar 1 pagina de alto",
    "preview_show_manual_scale": "Escala manual",
    "preview_rotate_button": "Girar",
    "preview_rotate_all_left_button": "Girar todo a la izquierda",
    "preview_rotate_left_button": "Girar a la izquierda",
    "preview_rotate_right_button": "Girar a la derecha",
    "preview_rotate_all_right_button": "Girar todo a la derecha",
    "preview_auto_rotate_button": "Auto rotate",
    "preview_optimize_button": "Optimizar",
    "preview_adjust_page_width_button": "Ajustar ancho de pagina",
    "preview_remove_page_button": "Eliminar pagina",
    "preview_move_page_button": "Mover pagina",
    "preview_import_button": "Importar",
    "preview_import_from_file_button": "Importar desde archivo",
    "preview_import_from_scanner_button": "Importar desde escáner",
    "preview_export_pages_button": "Exportar páginas",
    "import_pdf_dialog_title": "Importar PDF desde archivo",
    "import_pdf_source_label": "Nombre del archivo de origen",
    "import_pdf_browse_button": "Examinar...",
    "import_pdf_file_dialog_title": "Seleccionar archivo PDF",
    "import_pdf_destination_label": "Destino",
    "import_pdf_after_page": "Después de la página",
    "import_pdf_source_required": "Seleccione un archivo PDF para importar.",
    "export_pdf_pages_dialog_title": "Exportar páginas",
    "export_pdf_page_numbers_label": "Números de página",
    "export_pdf_file_name_label": "Nombre del archivo",
    "export_pdf_file_name_required": "Introduzca un nombre de archivo para la exportación.",
    "export_pdf_page_numbers_invalid": "Introduzca números de página como 1,3-5.",
    "export_pdf_save_dialog_title": "Guardar páginas exportadas",
    "move_page_dialog_title": "Mover pagina PDF",
    "move_page_source_label": "Pagina a mover:",
    "move_page_destination_label": "Destino:",
    "move_page_destination_page_label": "Numero de pagina:",
    "move_page_at_begin": "Al principio",
    "move_page_before": "Antes del numero",
    "move_page_after": "Despues del numero",
    "move_page_at_end": "Al final",
    "select_pdf_page": "Primero seleccione una pagina.",
    "confirm_remove_page": "Eliminar la pagina {page_no}?",
    "confirm_save_selected_file": "Guardar cambios en el archivo seleccionado?",
    "confirm_save_before_exit": "Tiene cambios no guardados en {count} archivo(s) PDF. Guardar antes de salir?",
    "confirm_delete": "Eliminar {path}?",
    "insert_before": "Insertar antes",
    "insert_after": "Insertar despues",
    "undo_no_action": "Nada que deshacer",
    "undo_done": "Deshacer completado",
    "undo_title": "Deshacer",
    "file_type_folder": "Carpeta",
    "file_type_file": "Archivo",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Optimizar todos los PDF",
    "tree_adjust_page_width_all_pdf": "Ajustar ancho de pagina para todos",
    "tree_no_folder_selected": "Seleccione primero una carpeta en el arbol.",
    "tree_no_folder_or_pdf_selected": "Seleccione primero una carpeta o un archivo PDF en el arbol.",
    "tree_optimize_all_done": "Optimizados: {optimized_count}\nFallidos: {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustados: {adjusted_count}\nFallidos: {failed_count}",
}
