TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "Назад",
    "forward_button": "Вперед",
    "exit_button": "Выход",
    "search_hint": "Поиск...",
    "show_hidden_checkbox": "Показывать скрытые",
    "name_column": "Имя",
    "type_column": "Тип",
    "size_column": "Размер",
    "preview_select_file": "Выберите файл для предпросмотра.",
    "folder_selected": "Выбрана папка:\n{path}",
    "no_preview_available": "Предпросмотр для этого элемента недоступен.",
    "unable_preview_pdf": "Не удалось просмотреть PDF.\n{exc}",
    "unable_preview_file": "Не удалось просмотреть файл.\n{exc}",
    "empty_file": "Этот файл пуст.",
    "preview_truncated_suffix": "\n\n... предпросмотр обрезан ...",
    "context_open": "Открыть",
    "context_rename": "Переименовать",
    "context_delete": "Удалить",
    "this_pc_root": "Этот компьютер",
    "tree_expand_placeholder": "...",
    "page_label": "Страница {page_no}/{page_count}",
    "showing_first_pages": "Показаны первые {shown_pages} страниц из {page_count}...",
    "page_move_error_title": "Перемещение страницы PDF",
    "unable_move_pdf_page": "Не удалось переместить страницу PDF.\n{exc}",
    "drop_overlay_label": "Перетащить на страницу {page_index}",
    "preview_edit_button": "Открыть",
    "preview_save_button": "Сохранить",
    "preview_delete_button": "Удалить файл",
    "preview_zoom_in_button": "Увеличить",
    "preview_zoom_out_button": "Уменьшить",
    "preview_rotate_button": "Повернуть",
    "preview_rotate_all_left_button": "Повернуть все влево",
    "preview_rotate_left_button": "Повернуть влево",
    "preview_rotate_right_button": "Повернуть вправо",
    "preview_rotate_all_right_button": "Повернуть все вправо",
    "preview_optimize_button": "Оптимизировать",
    "preview_ajust_page_width_button": "Подогнать ширину страницы",
    "preview_remove_page_button": "Удалить страницу",
    "preview_move_page_button": "Переместить страницу",
    "move_page_dialog_title": "Переместить страницу PDF",
    "move_page_source_label": "Страница для перемещения:",
    "move_page_destination_label": "Назначение:",
    "move_page_destination_page_label": "Номер страницы:",
    "move_page_at_begin": "В начало",
    "move_page_before": "Перед номером",
    "move_page_after": "После номера",
    "move_page_at_end": "В конец",
    "select_pdf_page": "Сначала выберите страницу.",
    "confirm_remove_page": "Удалить страницу {page_no}?",
    "confirm_save_selected_file": "Сохранить изменения в выбранном файле?",
    "confirm_save_before_exit": "Есть несохраненные изменения в {count} PDF-файле(ах). Сохранить перед выходом?",
    "confirm_delete": "Удалить {path}?",
    "insert_before": "Вставить перед",
    "insert_after": "Вставить после",
    "undo_no_action": "Нечего отменять",
    "undo_done": "Отмена выполнена",
    "undo_title": "Отменить",
    "file_type_folder": "Папка",
    "file_type_file": "Файл",
    "file_size_unit_kb": "КБ",
    "tree_optimize_all_pdf": "Оптимизировать все PDF",
    "tree_adjust_page_width_all_pdf": "Подогнать ширину страниц для всех",
    "tree_no_folder_selected": "Сначала выберите папку в дереве.",
    "tree_no_folder_or_pdf_selected": "Сначала выберите папку или PDF-файл в дереве.",
    "tree_optimize_all_done": "Оптимизировано: {optimized_count}\nОшибки: {failed_count}",
    "tree_adjust_page_width_all_done": "Подогнано: {adjusted_count}\nОшибки: {failed_count}",
}
