TRANSLATIONS = {
    "app_title": "Pdf Explorer",
    "back_button": "Zuruck",
    "forward_button": "Vorwarts",
    "exit_button": "Beenden",
    "search_hint": "Suchen...",
    "show_hidden_checkbox": "Versteckte anzeigen",
    "name_column": "Name",
    "type_column": "Typ",
    "size_column": "Grosse",
    "preview_select_file": "Datei zur Vorschau auswahlen.",
    "folder_selected": "Ordner ausgewahlt:\n{path}",
    "no_preview_available": "Fur dieses Element ist keine Vorschau verfugbar.",
    "unable_preview_pdf": "PDF-Vorschau nicht moglich.\n{exc}",
    "unable_preview_file": "Dateivorschau nicht moglich.\n{exc}",
    "empty_file": "Diese Datei ist leer.",
    "preview_truncated_suffix": "\n\n... Vorschau gekurzt ...",
    "context_open": "Offnen",
    "context_rename": "Umbenennen",
    "context_delete": "Loschen",
    "this_pc_root": "Dieser PC",
    "tree_expand_placeholder": "...",
    "page_label": "Seite {page_no}/{page_count}",
    "showing_first_pages": "Zeige die ersten {shown_pages} von {page_count} Seiten...",
    "page_move_error_title": "PDF-Seitenverschiebung",
    "unable_move_pdf_page": "PDF-Seite konnte nicht verschoben werden.\n{exc}",
    "drop_overlay_label": "Auf Seite {page_index} ablegen",
    "preview_edit_button": "Offnen",
    "preview_save_button": "Speichern",
    "preview_delete_button": "Datei loschen",
    "preview_zoom_in_button": "Vergrossern",
    "preview_zoom_out_button": "Verkleinern",
    "preview_rotate_button": "Drehen",
    "preview_rotate_all_left_button": "Alle nach links drehen",
    "preview_rotate_left_button": "Nach links drehen",
    "preview_rotate_right_button": "Nach rechts drehen",
    "preview_rotate_all_right_button": "Alle nach rechts drehen",
    "preview_optimize_button": "Optimieren",
    "preview_ajust_page_width_button": "Seitenbreite anpassen",
    "preview_remove_page_button": "Seite entfernen",
    "preview_move_page_button": "Seite verschieben",
    "move_page_dialog_title": "PDF-Seite verschieben",
    "move_page_source_label": "Zu verschiebende Seite:",
    "move_page_destination_label": "Ziel:",
    "move_page_destination_page_label": "Seitennummer:",
    "move_page_at_begin": "An den Anfang",
    "move_page_before": "Vor der Nummer",
    "move_page_after": "Nach der Nummer",
    "move_page_at_end": "An das Ende",
    "select_pdf_page": "Zuerst eine Seite auswahlen.",
    "confirm_remove_page": "Seite {page_no} entfernen?",
    "confirm_save_selected_file": "Anderungen an der ausgewahlten Datei speichern?",
    "confirm_save_before_exit": "Sie haben ungespeicherte Anderungen in {count} PDF-Datei(en). Vor dem Beenden speichern?",
    "confirm_delete": "{path} loschen?",
    "insert_before": "Davor einfugen",
    "insert_after": "Danach einfugen",
    "undo_no_action": "Nichts zum Ruckgangig machen",
    "undo_done": "Ruckgangig erfolgreich",
    "undo_title": "Ruckgangig",
    "file_type_folder": "Ordner",
    "file_type_file": "Datei",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Alle PDFs optimieren",
    "tree_adjust_page_width_all_pdf": "Seitenbreite fur alle anpassen",
    "tree_no_folder_selected": "Bitte zuerst einen Ordner im Baum auswahlen.",
    "tree_no_folder_or_pdf_selected": "Bitte zuerst einen Ordner oder eine PDF-Datei im Baum auswahlen.",
    "tree_optimize_all_done": "Optimiert: {optimized_count}\nFehlgeschlagen: {failed_count}",
    "tree_adjust_page_width_all_done": "Angepasst: {adjusted_count}\nFehlgeschlagen: {failed_count}",
}
