TRANSLATIONS = {
    "app_title": "Pdf проводник",
    "back_button": "Назад",
    "forward_button": "Вперед",
    "exit_button": "Выход",
    "search_hint": "Поиск...",
    "show_hidden_checkbox": "Показывать скрытые",
    "name_column": "Имя",
    "type_column": "Тип",
    "size_column": "Размер",
    "preview_select_file": "Выберите файл для предпросмотра.",
    "folder_selected": "Выбрана папка:\n{path}",
    "no_preview_available": "Предпросмотр для этого элемента недоступен.",
    "unable_preview_pdf": "Не удалось просмотреть PDF.\n{exc}",
    "unable_preview_file": "Не удалось просмотреть файл.\n{exc}",
    "empty_file": "Этот файл пуст.",
    "preview_truncated_suffix": "\n\n... предпросмотр обрезан ...",
    "context_open": "Открыть",
    "context_rename": "Переименовать",
    "context_delete": "Удалить",
    "scan": "Сканировать",
    "scan_dialog_title": "Сканирование документов",
    "scan_scanner_label": "Сканер",
    "scan_default_scanner": "Сканер по умолчанию",
    "scan_source_label": "Источник",
    "scan_source_flatbed": "Планшет",
    "scan_source_adf_simplex": "АПД (односторонний)",
    "scan_source_adf_duplex": "АПД (двусторонний)",
    "scan_color_mode_label": "Цветовой режим",
    "scan_color_mode_color": "Цветной",
    "scan_color_mode_grayscale": "Оттенки серого",
    "scan_color_mode_black_white": "Черно-белый",
    "scan_dpi_label": "Разрешение (DPI)",
    "scan_page_size_label": "Размер страницы",
    "scan_page_size_auto": "Авто",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Тип выходного файла",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Сканировать несколько страниц",
    "scan_output_file_label": "Выходной файл",
    "scan_browse_button": "Обзор...",
    "scan_open_after_label": "Открыть после сканирования",
    "scan_select_output_file_title": "Выберите выходной файл",
    "scan_button": "Сканировать",
    "scan_cancel_button": "Отмена",
    "scan_output_file_required": "Выберите выходной файл.",
    "scan_output_folder_not_exists": "Папка для сохранения не существует.",
    "scan_not_available_message": "Форма сканирования настроена. Интеграция со сканером пока недоступна в этой сборке.",
    "this_pc_root": "Этот компьютер",
    "tree_expand_placeholder": "...",
    "page_label": "Страница {page_no}/{page_count}",
    "showing_first_pages": "Показаны первые {shown_pages} страниц из {page_count}...",
    "page_move_error_title": "Перемещение страницы PDF",
    "unable_move_pdf_page": "Не удалось переместить страницу PDF.\n{exc}",
    "drop_overlay_label": "Перетащить на страницу {page_index}",
    "preview_edit_button": "Открыть",
    "preview_save_button": "Сохранить",
    "preview_cancel_button": "Отменить",
    "preview_save_as_button": "Сохранить как",
    "preview_delete_button": "Удалить файл",
    "preview_zoom_in_button": "Увеличить",
    "preview_zoom_out_button": "Уменьшить",
    "preview_show_mode": "Режим просмотра",
    "preview_show_1_page_wide": "1 страницу по ширине",
    "preview_show_2_pages_wide": "2 страницы по ширине",
    "preview_show_1_page_tall": "1 страницу по высоте",
    "preview_show_manual_scale": "Ручной масштаб",
    "preview_rotate_button": "Повернуть",
    "preview_rotate_all_left_button": "Повернуть все влево",
    "preview_rotate_left_button": "Повернуть влево",
    "preview_rotate_right_button": "Повернуть вправо",
    "preview_rotate_all_right_button": "Повернуть все вправо",
    "preview_auto_rotate_button": "Автоматическое вращение",
    "preview_optimize_button": "Оптимизировать",
    "preview_adjust_page_width_button": "Подогнать ширину страницы",
    "preview_remove_page_button": "Удалить страницу",
    "preview_move_page_button": "Переместить страницу",
    "preview_import_button": "Импорт",
    "preview_import_from_file_button": "Импортировать из файла",
    "preview_import_from_scanner_button": "Импортировать со сканера",
    "preview_export_pages_button": "Экспортировать страницы",
    "import_pdf_dialog_title": "Импорт PDF из файла",
    "import_pdf_source_label": "Имя исходного файла",
    "import_pdf_browse_button": "Обзор...",
    "import_pdf_file_dialog_title": "Выберите PDF файл",
    "import_pdf_destination_label": "Назначение",
    "import_pdf_after_page": "После страницы",
    "import_pdf_source_required": "Выберите PDF файл для импорта.",
    "export_pdf_pages_dialog_title": "Экспортировать страницы",
    "export_pdf_page_numbers_label": "Номера страниц",
    "export_pdf_file_name_label": "Имя файла",
    "export_pdf_file_name_required": "Введите имя файла для экспорта.",
    "export_pdf_page_numbers_invalid": "Введите номера страниц в формате 1,3-5.",
    "export_pdf_save_dialog_title": "Сохранить экспортированные страницы",
    "move_page_dialog_title": "Переместить страницу PDF",
    "move_page_source_label": "Страница для перемещения:",
    "move_page_destination_label": "Назначение:",
    "move_page_destination_page_label": "Номер страницы:",
    "move_page_at_begin": "В начало",
    "move_page_before": "Перед номером",
    "move_page_after": "После номера",
    "move_page_at_end": "В конец",
    "select_pdf_page": "Сначала выберите страницу.",
    "confirm_remove_page": "Удалить страницу {page_no}?",
    "confirm_save_selected_file": "Сохранить изменения в выбранном файле?",
    "confirm_save_before_exit": "Есть несохраненные изменения в {count} PDF-файле(ах). Сохранить перед выходом?",
    "confirm_delete": "Удалить {path}?",
    "insert_before": "Вставить перед",
    "insert_after": "Вставить после",
    "undo_no_action": "Нечего отменять",
    "undo_done": "Отмена выполнена",
    "undo_title": "Отменить",
    "file_type_folder": "Папка",
    "file_type_file": "Файл",
    "file_size_unit_kb": "КБ",
    "tree_optimize_all_pdf": "Оптимизировать все PDF",
    "tree_adjust_page_width_all_pdf": "Подогнать ширину страниц для всех",
    "tree_no_folder_selected": "Сначала выберите папку в дереве.",
    "tree_no_folder_or_pdf_selected": "Сначала выберите папку или PDF-файл в дереве.",
    "tree_optimize_all_done": "Оптимизировано: {optimized_count}\nОшибки: {failed_count}",
    "tree_adjust_page_width_all_done": "Подогнано: {adjusted_count}\nОшибки: {failed_count}",
}
