# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_help": "帮助",
    "menu_app_manual": "应用手册",
    "menu_about": "关于",
    "menu_file_options": "选项",
    "options_dialog_title": "选项",
    "options_group_main": "主要",
    "options_group_search": "搜索",
    "options_group_optimization": "优化",
    "options_group_preview": "预览",
    "options_group_scan": "扫描",
    "settings_ui_locale": "语言",
    "settings_show_hidden": "显示隐藏文件",
    "settings_preview_enabled": "启用预览",
    "settings_search_form_case_sensitive": "区分大小写",
    "settings_search_form_whole_word": "整词",
    "settings_search_form_word": "搜索 Word 文件",
    "settings_search_form_excel": "搜索 Excel 文件",
    "settings_optimize_pdf_image_width": "图片宽度",
    "settings_optimize_pdf_image_quality": "图片质量",
    "settings_optimize_pdf_color_target_dpi": "彩色目标 DPI",
    "settings_optimize_pdf_color_threshold_dpi": "彩色阈值 DPI",
    "settings_optimize_pdf_color_compression": "彩色压缩",
    "settings_optimize_pdf_color_quality": "彩色质量",
    "settings_optimize_pdf_mono_target_dpi": "单色目标 DPI",
    "settings_optimize_pdf_mono_threshold_dpi": "单色阈值 DPI",
    "settings_optimize_pdf_mono_compression": "单色压缩",
    "settings_optimize_pdf_compress_only_if_resized": "仅在调整大小时压缩",
    "settings_pdf_show_pages_limit": "PDF 页数限制",
    "settings_word_show_pages_limit": "Word 页数限制",
    "settings_excel_show_pages_limit": "Excel 页数限制",
    "settings_other_show_pages_limit": "其他页数限制",
    "settings_scan_file_type_index": "扫描文件类型",
    "settings_scan_multiple_pages": "扫描多页",
    "settings_scan_open_after": "扫描后打开",
    "back_button": "后退",
    "forward_button": "前进",
    "folder_up_button": "上级文件夹",
    "exit_button": "退出",
    "search_hint": "搜索...",
    "filter_label": "筛选",
    "search_in_files_button": "搜索文件",
    "search_in_files_dialog_title": "搜索文件",
    "search_query_label": "文本或正则表达式",
    "search_file_mask_label": "文件掩码",
    "search_clear_mask_tooltip": "清除掩码",
    "search_case_sensitive_checkbox": "区分大小写",
    "search_whole_word_checkbox": "整词",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "日期筛选",
    "search_pick_date_tooltip": "选择日期",
    "search_filter_all_dates": "所有日期",
    "search_filter_period": "时间段",
    "search_date_from": "从",
    "search_date_to": "到",
    "search_size_filter_label": "大小筛选",
    "search_filter_all_sizes": "所有大小",
    "search_filter_size": "大小",
    "search_size_from": "从",
    "search_size_to": "到",
    "search_folder_label": "搜索文件夹",
    "search_browse_button": "浏览...",
    "search_include_subfolders": "包含子文件夹",
    "search_mode_label": "搜索模式",
    "search_mode_text": "文本",
    "search_mode_regex": "正则表达式",
    "search_button": "搜索",
    "search_stop_button": "停止",
    "pause_button": "停止",
    "resume_button": "停止",
    "search_paused_status": "搜索已停止",
    "search_cancel_button": "退出",
    "search_result_short_name": "短文件名",
    "search_result_full_name": "完整文件名",
    "search_status_folder": "文件夹",
    "search_status_file": "文件",
    "search_finished_status": "搜索已完成",
    "search_no_results": "未找到文件",
    "search_results_count": "个结果",
    "search_query_required": "请输入要搜索的文本或正则表达式。",
    "search_no_folder": "请选择有效的搜索文件夹。",
    "search_invalid_regex": "无效的正则表达式：{error}",
    "search_select_folder_title": "选择搜索文件夹",
    "show_hidden_checkbox": "显示隐藏项",
    "name_column": "名称",
    "type_column": "类型",
    "size_column": "大小",
    "modified_column": "修改时间",
    "preview_select_file": "请选择要预览的文件。",
    "preview_checkbox_label": "预览",
    "folder_selected": "已选择文件夹:\n{path}",
    "no_preview_available": "此项目没有可用预览。",
    "unable_preview_pdf": "无法预览 PDF。\n{exc}",
    "unable_preview_file": "无法预览文件。\n{exc}",
    "empty_file": "该文件为空。",
    "preview_truncated_suffix": "\n\n... 预览已截断 ...",
    "context_open": "打开",
    "context_rename": "重命名",
    "context_new_folder": "新建文件夹",
    "restart_required_title": "需要重启",
    "restart_required_message": "语言设置已更改。请重启应用以应用新语言。",
    "context_refresh": "刷新",
    "context_print": "打印",
    "context_copy": "复制",
    "context_cut": "剪切",
    "context_paste": "粘贴",
    "context_delete": "删除",
    "ok_button": "确定",
    "cancel_button": "取消",
    "context_add_to_archive": "添加到存档",
    "context_extract_from_archive": "在此处从存档中提取",
    "context_extract_from_archive_here": "在此处从存档中提取",
    "context_extract_from_archive_into": "提取到指定文件夹",
    "archive_extract_folder_label": "文件夹路径",
    "archive_extract_select_folder_title": "选择目标文件夹",
    "scan": "扫描",
    "print_dialog_title": "打印",
    "print_universal_print_label": "服务",
    "print_printer_label": "打印机",
    "print_copies_label": "份数",
    "print_range_label": "打印范围",
    "print_range_all": "全部",
    "print_range_selection": "所选页",
    "print_file_label": "文档",
    "print_button": "打印",
    "print_parameters_button": "打印机参数",
    "print_cancel_button": "取消",
    "print_no_selection": "请选择要打印的文件。",
    "print_no_printer": "没有可用于 Microsoft Universal Print 的打印机。",
    "print_error_title": "打印错误",
    "print_error_unavailable": "此版本中不支持 Microsoft Universal Print。",
    "print_status_success": "已向 {printer} 发送打印任务。",
    "scan_dialog_title": "扫描文档",
    "scan_scanner_label": "扫描仪",
    "scan_default_scanner": "默认扫描仪",
    "scan_source_label": "来源",
    "scan_source_flatbed": "平板",
    "scan_source_adf_simplex": "ADF（单面）",
    "scan_source_adf_duplex": "ADF（双面）",
    "scan_color_mode_label": "颜色模式",
    "scan_color_mode_color": "彩色",
    "scan_color_mode_grayscale": "灰度",
    "scan_color_mode_black_white": "黑白",
    "scan_dpi_label": "分辨率 (DPI)",
    "scan_page_size_label": "页面大小",
    "scan_page_size_auto": "自动",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "输出类型",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "扫描多页",
    "scan_output_file_label": "输出文件",
    "scan_browse_button": "浏览...",
    "scan_open_after_label": "扫描后打开",
    "scan_select_output_file_title": "选择输出文件",
    "scan_button": "扫描",
    "scan_cancel_button": "取消",
    "scan_output_file_required": "请选择输出文件。",
    "scan_output_folder_not_exists": "输出文件夹不存在。",
    "scan_not_available_message": "扫描表单已配置。此版本暂不支持扫描仪集成。",
    "this_pc_root": "此电脑",
    "tree_expand_placeholder": "...",
    "page_label": "第 {page_no}/{page_count} 页",
    "showing_first_pages": "正在显示前 {shown_pages} 页，共 {page_count} 页...",
    "page_move_error_title": "PDF 页面移动",
    "unable_move_pdf_page": "无法移动 PDF 页面。\n{exc}",
    "drop_overlay_label": "拖放到第 {page_index} 页",
    "preview_edit_button": "打开",
    "preview_save_button": "保存",
    "preview_cancel_button": "取消",
    "preview_save_as_button": "另存为",
    "preview_delete_button": "删除文件",
    "preview_zoom_in_button": "放大",
    "preview_zoom_out_button": "缩小",
    "preview_show_mode": "显示模式",
    "preview_show_1_page_wide": "按宽度显示 1 页",
    "preview_show_2_pages_wide": "按宽度显示 2 页",
    "preview_show_1_page_tall": "按高度显示 1 页",
    "preview_show_manual_scale": "手动缩放",
    "preview_rotate_button": "旋转",
    "preview_rotate_all_left_button": "全部向左旋转",
    "preview_rotate_left_button": "向左旋转",
    "preview_rotate_right_button": "向右旋转",
    "preview_rotate_all_right_button": "全部向右旋转",
    "preview_auto_rotate_button": "自动旋转",
    "preview_optimize_button": "优化",
    "preview_adjust_page_width_button": "调整页面宽度",
    "preview_remove_page_button": "删除页面",
    "preview_move_page_button": "移动页面",
    "preview_load_all_button": "加载全部",
    "preview_pin_button": "固定标签页",
    "preview_unpin_button": "取消固定标签页",
    "preview_close_tab_button": "关闭标签页",
    "preview_import_button": "导入",
    "preview_import_from_file_button": "从文件导入",

    "preview_import_from_scanner_button": "从扫描仪导入",
    "preview_export_pages_button": "导出页面",
    "import_pdf_dialog_title": "从文件导入PDF",
    "import_pdf_source_label": "源文件名",
    "import_pdf_browse_button": "浏览...",
    "import_pdf_file_dialog_title": "选择PDF文件",
    "import_pdf_destination_label": "目标位置",
    "import_pdf_after_page": "在页面之后",
    "import_pdf_source_required": "请选择要导入的PDF文件。",
    "export_pdf_pages_dialog_title": "导出页面",
    "export_pdf_page_numbers_label": "页码",
    "export_pdf_file_name_label": "文件名",
    "export_pdf_file_name_required": "请输入导出文件名。",
    "export_pdf_page_numbers_invalid": "请输入类似 1,3-5 的页码。",
    "export_pdf_save_dialog_title": "保存导出的页面",
    "move_page_dialog_title": "移动 PDF 页面",
    "move_page_source_label": "要移动的页面:",
    "move_page_destination_label": "目标位置:",
    "move_page_destination_page_label": "页码:",
    "move_page_at_begin": "到开头",
    "move_page_before": "在该页码之前",
    "move_page_after": "在该页码之后",
    "move_page_at_end": "到末尾",
    "select_pdf_page": "请先选择页面。",
    "confirm_remove_page": "删除第 {page_no} 页吗?",
    "confirm_save_selected_file": "保存所选文件的更改吗?",
    "confirm_save_before_exit": "有 {count} 个 PDF 文件包含未保存更改。退出前是否保存?",
    "confirm_delete": "删除 {path} 吗?",
    "scan_overwrite_existing_prompt": "文件已存在:\n{path}\n\n是否覆盖此文件?\n选择“否”将使用带有 '(1)' 后缀的新文件名保存。",
    "insert_before": "在前面插入",
    "insert_after": "在后面插入",
    "undo_no_action": "没有可撤销的操作",
    "undo_done": "撤销成功",
    "undo_title": "撤销",
    "file_type_folder": "文件夹",
    "file_type_file": "文件",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "优化所有 PDF",
    "tree_adjust_page_width_all_pdf": "调整所有页面宽度",
    "tree_no_folder_selected": "请先在树中选择文件夹。",
    "tree_no_folder_or_pdf_selected": "请先在树中选择文件夹或 PDF 文件。",
    "tree_optimize_all_done": "已优化: {optimized_count}\n失败: {failed_count}",
    "tree_adjust_page_width_all_done": "已调整: {adjusted_count}\n失败: {failed_count}",
}
