TRANSLATIONS = {
    "app_title": "Python Explorer Pro",
    "back_button": "Back",
    "forward_button": "Forward",
    "search_hint": "Search...",
    "show_hidden_checkbox": "Show hidden",
    "name_column": "Name",
    "type_column": "Type",
    "size_column": "Size",
    "preview_select_file": "Select a file to preview.",
    "folder_selected": "Folder selected:\n{path}",
    "no_preview_available": "No preview available for this item.",
    "unable_preview_pdf": "Unable to preview PDF.\n{exc}",
    "unable_preview_file": "Unable to preview file.\n{exc}",
    "empty_file": "This file is empty.",
    "preview_truncated_suffix": "\n\n... preview truncated ...",
    "context_open": "Open",
    "context_rename": "Rename",
    "context_delete": "Delete",
    "this_pc_root": "This PC",
    "tree_expand_placeholder": "...",
    "page_label": "Page {page_no}/{page_count}",
    "showing_first_pages": "Showing first {shown_pages} pages of {page_count}...",
    "page_move_error_title": "PDF page move",
    "unable_move_pdf_page": "Unable to move PDF page.\n{exc}",
    "drop_overlay_label": "Drop on page {page_index}",
    "preview_edit_button": "Open",
    "preview_delete_button": "Delete",
    "preview_zoom_in_button": "Zoom In",
    "preview_zoom_out_button": "Zoom Out",
    "preview_rotate_button": "Rotate",
    "preview_rotate_all_left_button": "Rotate All Left",
    "preview_rotate_left_button": "Rotate Left",
    "preview_rotate_right_button": "Rotate Right",
    "preview_rotate_all_right_button": "Rotate All Right",
    "preview_optimize_button": "Optimize",
    "preview_ajust_page_width_button": "Ajust page width",
    "select_pdf_page": "Select a page first.",
    "confirm_delete": "Delete {path}?",
    "insert_before": "Insert before",
    "insert_after": "Insert after",
    "undo_no_action": "Nothing to undo",
    "undo_done": "Undo successful",
    "undo_title": "Undo",
    "file_type_folder": "Folder",
    "file_type_file": "File",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Optimize all PDF",
    "tree_no_folder_selected": "Select a folder in the tree first.",
    "tree_optimize_all_done": "Optimized: {optimized_count}\nFailed: {failed_count}",
}
