# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_file": "Fichier",
    "menu_navigation": "Navigation",
    "menu_document": "Document",
    "menu_help": "Aide",
    "menu_app_manual": "Manuel de l’application",
    "menu_about": "À propos",
    "menu_file_options": "Options",
    "options_dialog_title": "Options",
    "options_group_main": "Principal",
    "options_group_search": "Recherche",
    "options_group_optimization": "Optimisation",
    "options_group_preview": "Aperçu",
    "options_group_scan": "Numérisation",
    "settings_ui_locale": "Langue",
    "settings_show_hidden": "Afficher les fichiers cachés",
    "settings_preview_enabled": "Aperçu activé",
    "settings_search_form_case_sensitive": "Respecter la casse",
    "settings_search_form_whole_word": "Mot entier",
    "settings_search_form_word": "Rechercher les fichiers Word",
    "settings_search_form_excel": "Rechercher les fichiers Excel",
    "settings_optimize_pdf_image_width": "Largeur d'image",
    "settings_optimize_pdf_image_quality": "Qualité d'image",
    "settings_optimize_pdf_color_target_dpi": "DPI cible couleur",
    "settings_optimize_pdf_color_threshold_dpi": "Seuil DPI couleur",
    "settings_optimize_pdf_color_compression": "Compression couleur",
    "settings_optimize_pdf_color_quality": "Qualité couleur",
    "settings_optimize_pdf_mono_target_dpi": "DPI cible mono",
    "settings_optimize_pdf_mono_threshold_dpi": "Seuil DPI mono",
    "settings_optimize_pdf_mono_compression": "Compression mono",
    "settings_optimize_pdf_compress_only_if_resized": "Compresser uniquement si redimensionné",
    "settings_pdf_show_pages_limit": "Limite de pages PDF",
    "settings_word_show_pages_limit": "Limite de pages Word",
    "settings_excel_show_pages_limit": "Limite de pages Excel",
    "settings_other_show_pages_limit": "Limite de pages autres",
    "settings_scan_file_type_index": "Type de fichier de scan",
    "settings_scan_multiple_pages": "Scanner plusieurs pages",
    "settings_scan_open_after": "Ouvrir après le scan",
    "options_apply_button": "Appliquer",
    "options_cancel_button": "Annuler",
    "confirm_yes": "Oui",
    "confirm_no": "Non",
    "options_value_true": "Oui",
    "options_value_false": "Non",
    "options_value_empty": "Vide",
    "options_quality_low": "Faible",
    "options_quality_medium": "Moyenne",
    "options_quality_high": "Élevée",
    "locale_name_english": "Anglais",
    "locale_name_ukrainian": "Ukrainien",
    "locale_name_german": "Allemand",
    "locale_name_french": "Français",
    "locale_name_spanish": "Espagnol",
    "locale_name_italian": "Italien",
    "locale_name_portuguese_brazilian": "Portugais (Brésil)",
    "locale_name_japanese": "Japonais",
    "locale_name_korean": "Coréen",
    "locale_name_chinese_simplified": "Chinois (simplifié)",
    "locale_name_russian": "Russe",
    "back_button": "Retour",
    "forward_button": "Suivant",
    "folder_up_button": "Dossier parent",
    "exit_button": "Quitter",
    "search_hint": "Rechercher...",
    "filter_label": "Filtrer",
    "search_in_files_button": "Rechercher dans les fichiers",
    "search_in_files_dialog_title": "Rechercher dans les fichiers",
    "search_query_label": "Texte ou expression régulière",
    "search_file_mask_label": "Masque de fichier",
    "search_clear_mask_tooltip": "Effacer le masque",
    "search_case_sensitive_checkbox": "Respecter la casse",
    "search_whole_word_checkbox": "Mot entier",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "Filtre de date",
    "search_pick_date_tooltip": "Choisir une date",
    "search_filter_all_dates": "Toutes les dates",
    "search_filter_period": "Période",
    "search_date_from": "De",
    "search_date_to": "À",
    "search_size_filter_label": "Filtre de taille",
    "search_filter_all_sizes": "Toutes les tailles",
    "search_filter_size": "Taille",
    "search_size_from": "De",
    "search_size_to": "À",
    "search_folder_label": "Dossier de recherche",
    "search_browse_button": "Parcourir...",
    "search_include_subfolders": "Inclure les sous-dossiers",
    "search_mode_label": "Mode de recherche",
    "search_mode_text": "Texte",
    "search_mode_regex": "Expression régulière",
    "search_button": "Rechercher",
    "search_stop_button": "Arrêter",
    "pause_button": "Arrêter",
    "resume_button": "Arrêter",
    "search_paused_status": "Recherche arrêtée",
    "search_cancel_button": "Quitter",
    "search_result_short_name": "Nom court",
    "search_result_full_name": "Nom complet",
    "search_status_folder": "Dossier",
    "search_status_file": "Fichier",
    "search_finished_status": "La recherche est terminée",
    "search_no_results": "Aucun fichier trouvé",
    "search_results_count": "résultat(s)",
    "search_query_required": "Saisissez du texte ou une expression régulière.",
    "search_no_folder": "Sélectionnez un dossier de recherche valide.",
    "search_invalid_regex": "Expression régulière invalide : {error}",
    "search_select_folder_title": "Sélectionner le dossier de recherche",
    "show_hidden_checkbox": "Afficher les elements caches",
    "name_column": "Nom",
    "type_column": "Type",
    "size_column": "Taille",
    "modified_column": "Modifié",
    "preview_select_file": "Selectionnez un fichier pour l'apercu.",
    "preview_checkbox_label": "Aperçu",
    "folder_selected": "Dossier selectionne :\n{path}",
    "no_preview_available": "Aucun apercu disponible pour cet element.",
    "unable_preview_pdf": "Impossible d'afficher l'apercu PDF.\n{exc}",
    "unable_preview_file": "Impossible d'afficher l'apercu du fichier.\n{exc}",
    "empty_file": "Ce fichier est vide.",
    "preview_truncated_suffix": "\n\n... apercu tronque ...",
    "context_open": "Ouvrir",
    "context_rename": "Renommer",
    "context_new_folder": "Nouveau dossier",
    "restart_required_title": "Redémarrage requis",
    "restart_required_message": "Les paramètres de langue ont été modifiés. Redémarrez l’application pour appliquer la nouvelle langue.",
    "favorite_add_menu_item": "Ajouter aux favoris",
    "favorite_remove_menu_item": "Retirer des favoris",
    "favorite_column_header": "Favoris",
    "favorite_shortcuts_button": "Raccourcis standard",
    "standard_shortcuts_toggle_show_tooltip": "Afficher les raccourcis standard",
    "standard_shortcuts_toggle_hide_tooltip": "Masquer les raccourcis standard",
    "favorite_move_up_button": "Déplacer le panneau des favoris vers le haut",
    "favorite_move_down_button": "Déplacer le panneau des favoris vers le bas",
    "favorite_no_items": "Aucun favori",
    "context_refresh": "Actualiser",
    "context_restore": "Restaurer",
    "context_print": "Imprimer",
    "context_copy": "Copier",
    "context_cut": "Couper",
    "context_paste": "Coller",
    "context_remove_to_recycle_bin": "Supprimer vers la corbeille",
    "context_delete": "Supprimer définitivement",
    "ok_button": "OK",
    "cancel_button": "Annuler",
    "context_add_to_archive": "Ajouter à l'archive",
    "context_extract_from_archive": "Extraire de l'archive ici",
    "context_extract_from_archive_here": "Extraire de l'archive ici",
    "context_extract_from_archive_into": "Extraire de l'archive vers",
    "archive_extract_folder_label": "Chemin du dossier",
    "archive_extract_override": "Remplacer",
    "archive_extract_rename": "Renommer",
    "archive_extract_conflict_message": "Les fichiers suivants existent déjà dans {path} :\n{names}\n\nChoisissez la suite à donner.",
    "archive_extract_select_folder_title": "Sélectionner le dossier de destination",
    "scan": "Numeriser",
    "print_dialog_title": "Imprimer",
    "print_universal_print_label": "Service",
    "print_printer_label": "Imprimante",
    "print_copies_label": "Copies",
    "print_range_label": "Plage d'impression",
    "print_range_all": "Tout",
    "print_range_selection": "Pages sélectionnées",
    "print_file_label": "Document",
    "print_button": "Imprimer",
    "print_parameters_button": "Paramètres de l'imprimante",
    "print_cancel_button": "Annuler",
    "print_no_selection": "Sélectionnez un fichier à imprimer.",
    "print_no_printer": "Aucune imprimante n'est disponible pour Microsoft Universal Print.",
    "print_error_title": "Erreur d'impression",
    "print_error_unavailable": "Microsoft Universal Print n'est pas disponible dans cette version.",
    "print_status_success": "Travail d'impression envoyé à {printer}.",
    "scan_dialog_title": "Numériser des documents",
    "scan_scanner_label": "Scanner",
    "scan_default_scanner": "Scanner par défaut",
    "scan_source_label": "Source",
    "scan_source_flatbed": "À plat",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Duplex)",
    "scan_color_mode_label": "Mode couleur",
    "scan_color_mode_color": "Couleur",
    "scan_color_mode_grayscale": "Niveaux de gris",
    "scan_color_mode_black_white": "Noir et blanc",
    "scan_dpi_label": "Résolution (DPI)",
    "scan_page_size_label": "Taille de page",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Type de sortie",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Numériser plusieurs pages",
    "scan_output_file_label": "Fichier de sortie",
    "scan_browse_button": "Parcourir...",
    "scan_open_after_label": "Ouvrir après numérisation",
    "scan_select_output_file_title": "Sélectionner le fichier de sortie",
    "scan_button": "Numériser",
    "scan_cancel_button": "Annuler",
    "scan_output_file_required": "Sélectionnez un fichier de sortie.",
    "scan_output_folder_not_exists": "Le dossier de sortie n'existe pas.",
    "scan_not_available_message": "Le formulaire de numérisation est configuré. L'intégration du scanner n'est pas encore disponible dans cette version.",
    "this_pc_root": "Ce PC",
    "tree_expand_placeholder": "...",
    "page_label": "Page {page_no}/{page_count}",
    "showing_first_pages": "Affichage des {shown_pages} premieres pages sur {page_count}...",
    "page_move_error_title": "Deplacement de page PDF",
    "unable_move_pdf_page": "Impossible de deplacer la page PDF.\n{exc}",
    "drop_overlay_label": "Deposer sur la page {page_index}",
    "preview_edit_button": "Ouvrir",
    "preview_save_button": "Enregistrer",
    "preview_cancel_button": "Annuler",
    "preview_save_as_button": "Enregistrer sous",
    "preview_delete_button": "Supprimer le fichier",
    "preview_zoom_in_button": "Zoom avant",
    "preview_zoom_out_button": "Zoom arriere",
    "preview_show_mode": "Mode d'affichage",
    "preview_show_1_page_wide": "Afficher 1 page en largeur",
    "preview_show_2_pages_wide": "Afficher 2 pages en largeur",
    "preview_show_1_page_tall": "Afficher 1 page en hauteur",
    "preview_show_manual_scale": "Echelle manuelle",
    "preview_rotate_button": "Pivoter",
    "preview_rotate_all_left_button": "Tout pivoter a gauche",
    "preview_rotate_left_button": "Pivoter a gauche",
    "preview_rotate_right_button": "Pivoter a droite",
    "preview_rotate_all_right_button": "Tout pivoter a droite",
    "preview_auto_rotate_button": "Rotation automatique",
    "preview_optimize_button": "Optimiser",
    "preview_adjust_page_width_button": "Ajuster la largeur des pages",
    "preview_remove_page_button": "Supprimer la page",
    "preview_move_page_button": "Deplacer la page",
    "preview_load_all_button": "Tout charger",
    "preview_pin_button": "Épingler l'onglet",
    "preview_unpin_button": "Désépingler l'onglet",
    "preview_close_tab_button": "Fermer l'onglet",
    "preview_import_button": "Importer",
    "preview_import_from_file_button": "Importer depuis un fichier",

    "preview_import_from_scanner_button": "Importer depuis le scanner",
    "preview_export_pages_button": "Exporter des pages",
    "import_pdf_dialog_title": "Importer un PDF depuis un fichier",
    "import_pdf_source_label": "Nom du fichier source",
    "import_pdf_browse_button": "Parcourir...",
    "import_pdf_file_dialog_title": "Sélectionner un fichier PDF",
    "import_pdf_destination_label": "Destination",
    "import_pdf_after_page": "Après la page",
    "import_pdf_source_required": "Sélectionnez un fichier PDF à importer.",
    "export_pdf_pages_dialog_title": "Exporter des pages",
    "export_pdf_page_numbers_label": "Numéros de page",
    "export_pdf_file_name_label": "Nom du fichier",
    "export_pdf_file_name_required": "Saisissez un nom de fichier pour l'exportation.",
    "export_pdf_page_numbers_invalid": "Saisissez des numéros de page comme 1,3-5.",
    "export_pdf_save_dialog_title": "Enregistrer les pages exportées",
    "move_page_dialog_title": "Deplacer la page PDF",
    "move_page_source_label": "Page a deplacer:",
    "move_page_destination_label": "Destination:",
    "move_page_destination_page_label": "Numero de page:",
    "move_page_at_begin": "Au debut",
    "move_page_before": "Avant le numero",
    "move_page_after": "Apres le numero",
    "move_page_at_end": "A la fin",
    "select_pdf_page": "Selectionnez d'abord une page.",
    "confirm_remove_page": "Supprimer la page {page_no} ?",
    "confirm_save_selected_file": "Enregistrer les modifications du fichier selectionne ?",
    "confirm_save_before_exit": "Vous avez des modifications non enregistrees dans {count} fichier(s) PDF. Enregistrer avant de quitter ?",
    "confirm_delete": "Supprimer {path} ?",
    "scan_overwrite_existing_prompt": "Le fichier existe deja :\n{path}\n\nEcraser ce fichier ?\nChoisissez Non pour enregistrer un nouveau fichier avec le suffixe '(1)'.",
    "insert_before": "Inserer avant",
    "insert_after": "Inserer apres",
    "undo_no_action": "Rien a annuler",
    "undo_done": "Annulation reussie",
    "undo_title": "Annuler",
    "file_type_folder": "Dossier",
    "file_type_file": "Fichier",
    "file_size_unit_kb": "Ko",
    "tree_optimize_all_pdf": "Optimiser tous les PDF",
    "tree_adjust_page_width_all_pdf": "Ajuster la largeur des pages pour tous",
    "tree_no_folder_selected": "Selectionnez d'abord un dossier dans l'arborescence.",
    "tree_no_folder_or_pdf_selected": "Selectionnez d'abord un dossier ou un fichier PDF dans l'arborescence.",
    "tree_optimize_all_done": "Optimises : {optimized_count}\nEchecs : {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustes : {adjusted_count}\nEchecs : {failed_count}",
}
