# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_file": "Archivo",
    "menu_navigation": "Navegación",
    "menu_document": "Documento",
    "menu_help": "Ayuda",
    "menu_app_manual": "Manual de la aplicación",
    "menu_about": "Acerca de",
    "menu_file_options": "Opciones",
    "options_dialog_title": "Opciones",
    "options_group_main": "Principal",
    "options_group_search": "Búsqueda",
    "options_group_optimization": "Optimización",
    "options_group_preview": "Vista previa",
    "options_group_scan": "Escaneo",
    "settings_ui_locale": "Idioma",
    "settings_show_hidden": "Mostrar archivos ocultos",
    "settings_preview_enabled": "Vista previa habilitada",
    "settings_search_form_case_sensitive": "Distinguir mayúsculas",
    "settings_search_form_whole_word": "Palabra completa",
    "settings_search_form_word": "Buscar archivos Word",
    "settings_search_form_excel": "Buscar archivos Excel",
    "settings_optimize_pdf_image_width": "Ancho de imagen",
    "settings_optimize_pdf_image_quality": "Calidad de imagen",
    "settings_optimize_pdf_color_target_dpi": "DPI objetivo color",
    "settings_optimize_pdf_color_threshold_dpi": "Umbral DPI color",
    "settings_optimize_pdf_color_compression": "Compresión de color",
    "settings_optimize_pdf_color_quality": "Calidad de color",
    "settings_optimize_pdf_mono_target_dpi": "DPI objetivo monocromo",
    "settings_optimize_pdf_mono_threshold_dpi": "Umbral DPI monocromo",
    "settings_optimize_pdf_mono_compression": "Compresión monocroma",
    "settings_optimize_pdf_compress_only_if_resized": "Comprimir solo si se redimensiona",
    "settings_pdf_show_pages_limit": "Límite de páginas PDF",
    "settings_word_show_pages_limit": "Límite de páginas Word",
    "settings_excel_show_pages_limit": "Límite de páginas Excel",
    "settings_other_show_pages_limit": "Límite de páginas otras",
    "settings_scan_file_type_index": "Tipo de archivo de escaneo",
    "settings_scan_multiple_pages": "Escanear varias páginas",
    "settings_scan_open_after": "Abrir después del escaneo",
    "options_apply_button": "Aplicar",
    "options_cancel_button": "Cancelar",
    "confirm_yes": "Sí",
    "confirm_no": "No",
    "options_value_true": "Verdadero",
    "options_value_false": "Falso",
    "options_value_empty": "Vacío",
    "options_quality_low": "Baja",
    "options_quality_medium": "Media",
    "options_quality_high": "Alta",
    "locale_name_english": "Inglés",
    "locale_name_ukrainian": "Ucraniano",
    "locale_name_german": "Alemán",
    "locale_name_french": "Francés",
    "locale_name_spanish": "Español",
    "locale_name_italian": "Italiano",
    "locale_name_portuguese_brazilian": "Portugués (Brasil)",
    "locale_name_japanese": "Japonés",
    "locale_name_korean": "Coreano",
    "locale_name_chinese_simplified": "Chino (simplificado)",
    "locale_name_russian": "Ruso",
    "back_button": "Atras",
    "forward_button": "Adelante",
    "folder_up_button": "Subir carpeta",
    "exit_button": "Salir",
    "search_hint": "Buscar...",
    "filter_label": "Filtrar",
    "search_in_files_button": "Buscar en archivos",
    "search_in_files_dialog_title": "Buscar en archivos",
    "search_query_label": "Texto o expresión regular",
    "search_file_mask_label": "Máscara de archivo",
    "search_clear_mask_tooltip": "Borrar máscara",
    "search_case_sensitive_checkbox": "Distinguir mayúsculas",
    "search_whole_word_checkbox": "Palabra completa",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "Filtro por fecha",
    "search_pick_date_tooltip": "Elegir fecha",
    "search_filter_all_dates": "Todas las fechas",
    "search_filter_period": "Período",
    "search_date_from": "Desde",
    "search_date_to": "Hasta",
    "search_size_filter_label": "Filtro por tamaño",
    "search_filter_all_sizes": "Todos los tamaños",
    "search_filter_size": "Tamaño",
    "search_size_from": "Desde",
    "search_size_to": "Hasta",
    "search_folder_label": "Carpeta de búsqueda",
    "search_browse_button": "Examinar...",
    "search_include_subfolders": "Incluir carpetas secundarias",
    "search_mode_label": "Modo de búsqueda",
    "search_mode_text": "Texto",
    "search_mode_regex": "Expresión regular",
    "search_button": "Buscar",
    "search_stop_button": "Detener",
    "pause_button": "Detener",
    "resume_button": "Detener",
    "search_paused_status": "Búsqueda detenida",
    "search_cancel_button": "Salir",
    "search_result_short_name": "Nombre corto",
    "search_result_full_name": "Nombre completo",
    "search_status_folder": "Carpeta",
    "search_status_file": "Archivo",
    "search_finished_status": "La búsqueda ha terminado",
    "search_no_results": "No se encontraron archivos",
    "search_results_count": "resultado(s)",
    "search_query_required": "Ingrese texto o una expresión regular para buscar.",
    "search_no_folder": "Seleccione una carpeta de búsqueda válida.",
    "search_invalid_regex": "Expresión regular no válida: {error}",
    "search_select_folder_title": "Seleccionar carpeta de búsqueda",
    "show_hidden_checkbox": "Mostrar ocultos",
    "name_column": "Nombre",
    "type_column": "Tipo",
    "size_column": "Tamano",
    "modified_column": "Modificado",
    "preview_select_file": "Seleccione un archivo para previsualizar.",
    "preview_checkbox_label": "Vista previa",
    "folder_selected": "Carpeta seleccionada:\n{path}",
    "no_preview_available": "No hay vista previa disponible para este elemento.",
    "unable_preview_pdf": "No se puede previsualizar el PDF.\n{exc}",
    "unable_preview_file": "No se puede previsualizar el archivo.\n{exc}",
    "empty_file": "Este archivo esta vacio.",
    "preview_truncated_suffix": "\n\n... vista previa recortada ...",
    "context_open": "Abrir",
    "context_rename": "Renombrar",
    "context_new_folder": "Nueva carpeta",
    "restart_required_title": "Se requiere reinicio",
    "restart_required_message": "Se cambiaron los ajustes de idioma. Reinicie la aplicación para aplicar el nuevo idioma.",
    "favorite_add_menu_item": "Añadir a favoritos",
    "favorite_remove_menu_item": "Quitar de favoritos",
    "favorite_column_header": "Favoritos",
    "favorite_shortcuts_button": "Accesos directos estándar",
    "standard_shortcuts_toggle_show_tooltip": "Mostrar accesos directos estándar",
    "standard_shortcuts_toggle_hide_tooltip": "Ocultar accesos directos estándar",
    "favorite_move_up_button": "Mover panel de favoritos arriba",
    "favorite_move_down_button": "Mover panel de favoritos abajo",
    "favorite_no_items": "Sin favoritos",
    "context_refresh": "Actualizar",
    "context_print": "Imprimir",
    "context_copy": "Copiar",
    "context_cut": "Cortar",
    "context_paste": "Pegar",
    "context_remove_to_recycle_bin": "Mover a la Papelera de reciclaje",
    "context_delete": "Eliminar permanentemente",
    "ok_button": "Aceptar",
    "cancel_button": "Cancelar",
    "context_add_to_archive": "Agregar al archivo",
    "context_extract_from_archive": "Extraer del archivo aquí",
    "context_extract_from_archive_here": "Extraer del archivo aquí",
    "context_extract_from_archive_into": "Extraer del archivo en",
    "archive_extract_folder_label": "Ruta de la carpeta",
    "archive_extract_override": "Sobrescribir",
    "archive_extract_rename": "Renombrar",
    "archive_extract_conflict_message": "Los siguientes archivos ya existen en {path}:\n{names}\n\nElija cómo continuar.",
    "archive_extract_select_folder_title": "Seleccionar carpeta de destino",
    "scan": "Escanear",
    "print_dialog_title": "Imprimir",
    "print_universal_print_label": "Servicio",
    "print_printer_label": "Impresora",
    "print_copies_label": "Copias",
    "print_range_label": "Intervalo",
    "print_range_all": "Todo",
    "print_range_selection": "Páginas seleccionadas",
    "print_file_label": "Documento",
    "print_button": "Imprimir",
    "print_parameters_button": "Parámetros de impresora",
    "print_cancel_button": "Cancelar",
    "print_no_selection": "Seleccione un archivo para imprimir.",
    "print_no_printer": "No hay impresoras disponibles para Microsoft Universal Print.",
    "print_error_title": "Error de impresión",
    "print_error_unavailable": "Microsoft Universal Print no está disponible en esta versión.",
    "print_status_success": "Trabajo de impresión enviado a {printer}.",
    "scan_dialog_title": "Escanear documentos",
    "scan_scanner_label": "Escáner",
    "scan_default_scanner": "Escáner predeterminado",
    "scan_source_label": "Origen",
    "scan_source_flatbed": "Cama plana",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Dúplex)",
    "scan_color_mode_label": "Modo de color",
    "scan_color_mode_color": "Color",
    "scan_color_mode_grayscale": "Escala de grises",
    "scan_color_mode_black_white": "Blanco y negro",
    "scan_dpi_label": "Resolución (DPI)",
    "scan_page_size_label": "Tamaño de página",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Tipo de salida",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Escanear varias páginas",
    "scan_output_file_label": "Archivo de salida",
    "scan_browse_button": "Examinar...",
    "scan_open_after_label": "Abrir después de escanear",
    "scan_select_output_file_title": "Seleccionar archivo de salida",
    "scan_button": "Escanear",
    "scan_cancel_button": "Cancelar",
    "scan_output_file_required": "Seleccione un archivo de salida.",
    "scan_output_folder_not_exists": "La carpeta de salida no existe.",
    "scan_not_available_message": "El formulario de escaneo está configurado. La integración con el escáner aún no está disponible en esta versión.",
    "this_pc_root": "Este equipo",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrando las primeras {shown_pages} paginas de {page_count}...",
    "page_move_error_title": "Mover pagina PDF",
    "unable_move_pdf_page": "No se pudo mover la pagina PDF.\n{exc}",
    "drop_overlay_label": "Soltar en la pagina {page_index}",
    "preview_edit_button": "Abrir",
    "preview_save_button": "Guardar",
    "preview_cancel_button": "Cancelar",
    "preview_save_as_button": "Guardar como",
    "preview_delete_button": "Eliminar archivo",
    "preview_zoom_in_button": "Acercar",
    "preview_zoom_out_button": "Alejar",
    "preview_show_mode": "Modo de visualizacion",
    "preview_show_1_page_wide": "Mostrar 1 pagina de ancho",
    "preview_show_2_pages_wide": "Mostrar 2 paginas de ancho",
    "preview_show_1_page_tall": "Mostrar 1 pagina de alto",
    "preview_show_manual_scale": "Escala manual",
    "preview_rotate_button": "Girar",
    "preview_rotate_all_left_button": "Girar todo a la izquierda",
    "preview_rotate_left_button": "Girar a la izquierda",
    "preview_rotate_right_button": "Girar a la derecha",
    "preview_rotate_all_right_button": "Girar todo a la derecha",
    "preview_auto_rotate_button": "Rotación automática",
    "preview_optimize_button": "Optimizar",
    "preview_adjust_page_width_button": "Ajustar ancho de pagina",
    "preview_remove_page_button": "Eliminar pagina",
    "preview_move_page_button": "Mover pagina",
    "preview_load_all_button": "Cargar todo",
    "preview_pin_button": "Anclar pestaña",
    "preview_unpin_button": "Desanclar pestaña",
    "preview_close_tab_button": "Cerrar pestaña",
    "preview_import_button": "Importar",
    "preview_import_from_file_button": "Importar desde archivo",

    "preview_import_from_scanner_button": "Importar desde escáner",
    "preview_export_pages_button": "Exportar páginas",
    "import_pdf_dialog_title": "Importar PDF desde archivo",
    "import_pdf_source_label": "Nombre del archivo de origen",
    "import_pdf_browse_button": "Examinar...",
    "import_pdf_file_dialog_title": "Seleccionar archivo PDF",
    "import_pdf_destination_label": "Destino",
    "import_pdf_after_page": "Después de la página",
    "import_pdf_source_required": "Seleccione un archivo PDF para importar.",
    "export_pdf_pages_dialog_title": "Exportar páginas",
    "export_pdf_page_numbers_label": "Números de página",
    "export_pdf_file_name_label": "Nombre del archivo",
    "export_pdf_file_name_required": "Introduzca un nombre de archivo para la exportación.",
    "export_pdf_page_numbers_invalid": "Introduzca números de página como 1,3-5.",
    "export_pdf_save_dialog_title": "Guardar páginas exportadas",
    "move_page_dialog_title": "Mover pagina PDF",
    "move_page_source_label": "Pagina a mover:",
    "move_page_destination_label": "Destino:",
    "move_page_destination_page_label": "Numero de pagina:",
    "move_page_at_begin": "Al principio",
    "move_page_before": "Antes del numero",
    "move_page_after": "Despues del numero",
    "move_page_at_end": "Al final",
    "select_pdf_page": "Primero seleccione una pagina.",
    "confirm_remove_page": "Eliminar la pagina {page_no}?",
    "confirm_save_selected_file": "Guardar cambios en el archivo seleccionado?",
    "confirm_save_before_exit": "Tiene cambios no guardados en {count} archivo(s) PDF. Guardar antes de salir?",
    "confirm_delete": "Eliminar {path}?",
    "scan_overwrite_existing_prompt": "El archivo ya existe:\n{path}\n\nDesea sobrescribir este archivo?\nElija No para guardar como un archivo nuevo con el sufijo '(1)'.",
    "insert_before": "Insertar antes",
    "insert_after": "Insertar despues",
    "undo_no_action": "Nada que deshacer",
    "undo_done": "Deshacer completado",
    "undo_title": "Deshacer",
    "file_type_folder": "Carpeta",
    "file_type_file": "Archivo",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Optimizar todos los PDF",
    "tree_adjust_page_width_all_pdf": "Ajustar ancho de pagina para todos",
    "tree_no_folder_selected": "Seleccione primero una carpeta en el arbol.",
    "tree_no_folder_or_pdf_selected": "Seleccione primero una carpeta o un archivo PDF en el arbol.",
    "tree_optimize_all_done": "Optimizados: {optimized_count}\nFallidos: {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustados: {adjusted_count}\nFallidos: {failed_count}",
}
