# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_help": "ヘルプ",
    "menu_app_manual": "アプリマニュアル",
    "menu_about": "情報",
    "menu_file_options": "オプション",
    "options_dialog_title": "オプション",
    "options_group_main": "メイン",
    "options_group_search": "検索",
    "options_group_optimization": "最適化",
    "options_group_preview": "プレビュー",
    "options_group_scan": "スキャン",
    "settings_ui_locale": "言語",
    "settings_show_hidden": "隠しファイルを表示",
    "settings_preview_enabled": "プレビューを有効化",
    "settings_search_form_case_sensitive": "大文字小文字を区別",
    "settings_search_form_whole_word": "単語全体",
    "settings_search_form_word": "Word ファイルを検索",
    "settings_search_form_excel": "Excel ファイルを検索",
    "settings_optimize_pdf_image_width": "画像幅",
    "settings_optimize_pdf_image_quality": "画像品質",
    "settings_optimize_pdf_color_target_dpi": "カラー目標 DPI",
    "settings_optimize_pdf_color_threshold_dpi": "カラー閾値 DPI",
    "settings_optimize_pdf_color_compression": "カラー圧縮",
    "settings_optimize_pdf_color_quality": "カラー品質",
    "settings_optimize_pdf_mono_target_dpi": "モノクロ目標 DPI",
    "settings_optimize_pdf_mono_threshold_dpi": "モノクロ閾値 DPI",
    "settings_optimize_pdf_mono_compression": "モノクロ圧縮",
    "settings_optimize_pdf_compress_only_if_resized": "サイズ変更時のみ圧縮",
    "settings_pdf_show_pages_limit": "PDF ページ制限",
    "settings_word_show_pages_limit": "Word ページ制限",
    "settings_excel_show_pages_limit": "Excel ページ制限",
    "settings_other_show_pages_limit": "その他ページ制限",
    "settings_scan_file_type_index": "スキャン形式",
    "settings_scan_multiple_pages": "複数ページをスキャン",
    "settings_scan_open_after": "スキャン後に開く",
    "back_button": "戻る",
    "forward_button": "進む",
    "folder_up_button": "上のフォルダー",
    "exit_button": "終了",
    "search_hint": "検索...",
    "filter_label": "フィルター",
    "search_in_files_button": "ファイル内検索",
    "search_in_files_dialog_title": "ファイル内検索",
    "search_query_label": "テキストまたは正規表現",
    "search_file_mask_label": "ファイルマスク",
    "search_clear_mask_tooltip": "マスクをクリア",
    "search_case_sensitive_checkbox": "大文字小文字を区別",
    "search_whole_word_checkbox": "単語全体",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "日付フィルター",
    "search_pick_date_tooltip": "日付を選択",
    "search_filter_all_dates": "すべての日付",
    "search_filter_period": "期間",
    "search_date_from": "開始",
    "search_date_to": "終了",
    "search_size_filter_label": "サイズ フィルター",
    "search_filter_all_sizes": "すべてのサイズ",
    "search_filter_size": "サイズ",
    "search_size_from": "開始",
    "search_size_to": "終了",
    "search_folder_label": "検索フォルダー",
    "search_browse_button": "参照...",
    "search_include_subfolders": "サブフォルダーを含める",
    "search_mode_label": "検索モード",
    "search_mode_text": "テキスト",
    "search_mode_regex": "正規表現",
    "search_button": "検索",
    "search_stop_button": "停止",
    "pause_button": "停止",
    "resume_button": "停止",
    "search_paused_status": "検索を停止しました",
    "search_cancel_button": "終了",
    "search_result_short_name": "短いファイル名",
    "search_result_full_name": "完全なファイル名",
    "search_status_folder": "フォルダー",
    "search_status_file": "ファイル",
    "search_finished_status": "検索が完了しました",
    "search_no_results": "ファイルが見つかりませんでした",
    "search_results_count": "件",
    "search_query_required": "検索するテキストまたは正規表現を入力してください。",
    "search_no_folder": "有効な検索フォルダーを選択してください。",
    "search_invalid_regex": "正規表現が無効です: {error}",
    "search_select_folder_title": "検索フォルダーを選択",
    "show_hidden_checkbox": "隠しファイルを表示",
    "name_column": "名前",
    "type_column": "種類",
    "size_column": "サイズ",
    "modified_column": "更新日時",
    "preview_select_file": "プレビューするファイルを選択してください。",
    "preview_checkbox_label": "プレビュー",
    "folder_selected": "選択したフォルダー:\n{path}",
    "no_preview_available": "この項目のプレビューは利用できません。",
    "unable_preview_pdf": "PDF をプレビューできません。\n{exc}",
    "unable_preview_file": "ファイルをプレビューできません。\n{exc}",
    "empty_file": "このファイルは空です。",
    "preview_truncated_suffix": "\n\n... プレビューは省略されました ...",
    "context_open": "開く",
    "context_rename": "名前変更",
    "context_new_folder": "新しいフォルダー",
    "restart_required_title": "再起動が必要です",
    "restart_required_message": "言語設定が変更されました。新しい言語を適用するにはアプリケーションを再起動してください。",
    "context_refresh": "更新",
    "context_print": "印刷",
    "context_copy": "コピー",
    "context_cut": "切り取り",
    "context_paste": "貼り付け",
    "context_delete": "削除",
    "context_add_to_archive": "アーカイブに追加",
    "context_extract_from_archive": "アーカイブから抽出",
    "scan": "スキャン",
    "print_dialog_title": "印刷",
    "print_universal_print_label": "サービス",
    "print_printer_label": "プリンター",
    "print_copies_label": "部数",
    "print_range_label": "印刷範囲",
    "print_range_all": "全体",
    "print_range_selection": "選択ページ",
    "print_file_label": "ドキュメント",
    "print_button": "印刷",
    "print_parameters_button": "プリンター設定",
    "print_cancel_button": "キャンセル",
    "print_no_selection": "印刷するファイルを選択してください。",
    "print_no_printer": "Microsoft Universal Print に利用可能なプリンターがありません。",
    "print_error_title": "印刷エラー",
    "print_error_unavailable": "このビルドでは Microsoft Universal Print は利用できません。",
    "print_status_success": "{printer} に印刷ジョブを送信しました。",
    "scan_dialog_title": "ドキュメントをスキャン",
    "scan_scanner_label": "スキャナー",
    "scan_default_scanner": "既定のスキャナー",
    "scan_source_label": "ソース",
    "scan_source_flatbed": "フラットベッド",
    "scan_source_adf_simplex": "ADF（片面）",
    "scan_source_adf_duplex": "ADF（両面）",
    "scan_color_mode_label": "カラーモード",
    "scan_color_mode_color": "カラー",
    "scan_color_mode_grayscale": "グレースケール",
    "scan_color_mode_black_white": "白黒",
    "scan_dpi_label": "解像度 (DPI)",
    "scan_page_size_label": "ページサイズ",
    "scan_page_size_auto": "自動",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "出力タイプ",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "複数ページをスキャン",
    "scan_output_file_label": "出力ファイル",
    "scan_browse_button": "参照...",
    "scan_open_after_label": "スキャン後に開く",
    "scan_select_output_file_title": "出力ファイルを選択",
    "scan_button": "スキャン",
    "scan_cancel_button": "キャンセル",
    "scan_output_file_required": "出力ファイルを選択してください。",
    "scan_output_folder_not_exists": "出力フォルダーが存在しません。",
    "scan_not_available_message": "スキャンフォームは設定されました。このビルドではスキャナー連携はまだ利用できません。",
    "this_pc_root": "この PC",
    "tree_expand_placeholder": "...",
    "page_label": "ページ {page_no}/{page_count}",
    "showing_first_pages": "{page_count} ページ中、先頭 {shown_pages} ページを表示しています...",
    "page_move_error_title": "PDF ページ移動",
    "unable_move_pdf_page": "PDF ページを移動できません。\n{exc}",
    "drop_overlay_label": "ページ {page_index} にドロップ",
    "preview_edit_button": "開く",
    "preview_save_button": "保存",
    "preview_cancel_button": "キャンセル",
    "preview_save_as_button": "名前を付けて保存",
    "preview_delete_button": "ファイルを削除",
    "preview_zoom_in_button": "拡大",
    "preview_zoom_out_button": "縮小",
    "preview_show_mode": "表示モード",
    "preview_show_1_page_wide": "横に1ページ表示",
    "preview_show_2_pages_wide": "横に2ページ表示",
    "preview_show_1_page_tall": "縦に1ページ表示",
    "preview_show_manual_scale": "手動スケール",
    "preview_rotate_button": "回転",
    "preview_rotate_all_left_button": "すべて左回転",
    "preview_rotate_left_button": "左回転",
    "preview_rotate_right_button": "右回転",
    "preview_rotate_all_right_button": "すべて右回転",
    "preview_auto_rotate_button": "自動回転",
    "preview_optimize_button": "最適化",
    "preview_adjust_page_width_button": "ページ幅を調整",
    "preview_remove_page_button": "ページを削除",
    "preview_move_page_button": "ページを移動",
    "preview_load_all_button": "すべて読み込む",
    "preview_pin_button": "タブを固定",
    "preview_unpin_button": "タブの固定を解除",
    "preview_close_tab_button": "タブを閉じる",
    "preview_import_button": "インポート",
    "preview_import_from_file_button": "ファイルからインポート",

    "preview_import_from_scanner_button": "スキャナーからインポート",
    "preview_export_pages_button": "ページをエクスポート",
    "import_pdf_dialog_title": "ファイルからPDFをインポート",
    "import_pdf_source_label": "元ファイル名",
    "import_pdf_browse_button": "参照...",
    "import_pdf_file_dialog_title": "PDFファイルを選択",
    "import_pdf_destination_label": "挿入先",
    "import_pdf_after_page": "ページの後",
    "import_pdf_source_required": "インポートするPDFファイルを選択してください。",
    "export_pdf_pages_dialog_title": "ページをエクスポート",
    "export_pdf_page_numbers_label": "ページ番号",
    "export_pdf_file_name_label": "ファイル名",
    "export_pdf_file_name_required": "エクスポートするファイル名を入力してください。",
    "export_pdf_page_numbers_invalid": "1,3-5 のようにページ番号を入力してください。",
    "export_pdf_save_dialog_title": "エクスポートしたページを保存",
    "move_page_dialog_title": "PDFページを移動",
    "move_page_source_label": "移動するページ:",
    "move_page_destination_label": "移動先:",
    "move_page_destination_page_label": "ページ番号:",
    "move_page_at_begin": "先頭へ",
    "move_page_before": "番号の前",
    "move_page_after": "番号の後",
    "move_page_at_end": "末尾へ",
    "select_pdf_page": "先にページを選択してください。",
    "confirm_remove_page": "ページ {page_no} を削除しますか?",
    "confirm_save_selected_file": "選択したファイルへの変更を保存しますか?",
    "confirm_save_before_exit": "{count} 個の PDF ファイルに未保存の変更があります。終了前に保存しますか?",
    "confirm_delete": "{path} を削除しますか?",
    "scan_overwrite_existing_prompt": "ファイルは既に存在します:\n{path}\n\nこのファイルを上書きしますか?\n「いいえ」を選ぶと、'(1)' サフィックス付きの新しいファイル名で保存します。",
    "insert_before": "前に挿入",
    "insert_after": "後に挿入",
    "undo_no_action": "元に戻す操作はありません",
    "undo_done": "元に戻しました",
    "undo_title": "元に戻す",
    "file_type_folder": "フォルダー",
    "file_type_file": "ファイル",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "すべての PDF を最適化",
    "tree_adjust_page_width_all_pdf": "すべてのページ幅を調整",
    "tree_no_folder_selected": "先にツリーでフォルダーを選択してください。",
    "tree_no_folder_or_pdf_selected": "先にツリーでフォルダーまたは PDF ファイルを選択してください。",
    "tree_optimize_all_done": "最適化: {optimized_count}\n失敗: {failed_count}",
    "tree_adjust_page_width_all_done": "調整: {adjusted_count}\n失敗: {failed_count}",
}
