# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_file": "Файл",
    "menu_navigation": "Навігація",
    "menu_document": "Документ",
    "menu_help": "Допомога",
    "menu_app_manual": "Керівництво",
    "menu_about": "Про програму",
    "menu_file_options": "Параметри",
    "options_dialog_title": "Параметри",
    "options_group_main": "Основні",
    "options_group_search": "Пошук",
    "options_group_optimization": "Оптимізація",
    "options_group_preview": "Попередній перегляд",
    "options_group_scan": "Сканування",
    "settings_ui_locale": "Мова",
    "settings_show_hidden": "Показувати приховані файли",
    "settings_preview_enabled": "Показувати попередній перегляд",
    "settings_search_form_case_sensitive": "З урахуванням регістру",
    "settings_search_form_whole_word": "Ціле слово",
    "settings_search_form_word": "Шукати Word-файли",
    "settings_search_form_excel": "Шукати Excel-файли",
    "settings_optimize_pdf_image_width": "Ширина зображення",
    "settings_optimize_pdf_image_quality": "Якість зображення",
    "settings_optimize_pdf_color_target_dpi": "Цільове DPI для кольорових",
    "settings_optimize_pdf_color_threshold_dpi": "Поріг DPI для кольорових",
    "settings_optimize_pdf_color_compression": "Стиснення кольорових",
    "settings_optimize_pdf_color_quality": "Якість кольорових",
    "settings_optimize_pdf_mono_target_dpi": "Цільове DPI для монохромних",
    "settings_optimize_pdf_mono_threshold_dpi": "Поріг DPI для монохромних",
    "settings_optimize_pdf_mono_compression": "Стиснення монохромних",
    "settings_optimize_pdf_compress_only_if_resized": "Стисняти лише при зміні розміру",
    "settings_pdf_show_pages_limit": "Ліміт сторінок PDF",
    "settings_word_show_pages_limit": "Ліміт сторінок Word",
    "settings_excel_show_pages_limit": "Ліміт сторінок Excel",
    "settings_other_show_pages_limit": "Ліміт сторінок інших типів",
    "settings_scan_file_type_index": "Тип файлу сканування",
    "settings_scan_multiple_pages": "Сканувати кілька сторінок",
    "settings_scan_open_after": "Відкрити після сканування",
    "options_apply_button": "Застосувати",
    "options_cancel_button": "Скасувати",
    "confirm_yes": "Так",
    "confirm_no": "Ні",
    "options_value_true": "Так",
    "options_value_false": "Ні",
    "options_value_empty": "Порожньо",
    "options_quality_low": "Низька",
    "options_quality_medium": "Середня",
    "options_quality_high": "Висока",
    "locale_name_english": "Англійська",
    "locale_name_ukrainian": "Українська",
    "locale_name_german": "Німецька",
    "locale_name_french": "Французька",
    "locale_name_spanish": "Іспанська",
    "locale_name_italian": "Італійська",
    "locale_name_portuguese_brazilian": "Португальська (Бразилія)",
    "locale_name_japanese": "Японська",
    "locale_name_korean": "Корейська",
    "locale_name_chinese_simplified": "Китайська (спрощена)",
    "locale_name_russian": "Російська",
    "back_button": "Назад",
    "forward_button": "Вперед",
    "folder_up_button": "На рівень вгору",
    "exit_button": "Вихід",
    "search_hint": "Пошук...",
    "filter_label": "Фільтр",
    "search_in_files_button": "Пошук у файлах",
    "search_in_files_dialog_title": "Пошук у файлах",
    "search_query_label": "Текст або регулярний вираз",
    "search_file_mask_label": "Маска файлів",
    "search_clear_mask_tooltip": "Очистити маску",
    "search_case_sensitive_checkbox": "З урахуванням регістру",
    "search_whole_word_checkbox": "Ціле слово",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "Фільтр за датою",
    "search_pick_date_tooltip": "Вибрати дату",
    "search_filter_all_dates": "Усі дати",
    "search_filter_period": "Період",
    "search_date_from": "Від",
    "search_date_to": "До",
    "search_size_filter_label": "Фільтр за розміром",
    "search_filter_all_sizes": "Усі розміри",
    "search_filter_size": "Розмір",
    "search_size_from": "Від",
    "search_size_to": "До",
    "search_folder_label": "Папка пошуку",
    "search_browse_button": "Огляд...",
    "search_include_subfolders": "Шукати у вкладених папках",
    "search_mode_label": "Режим пошуку",
    "search_mode_text": "Текст",
    "search_mode_regex": "Регулярний вираз",
    "search_button": "Пошук",
    "search_stop_button": "Стоп",
    "pause_button": "Стоп",
    "resume_button": "Стоп",
    "search_paused_status": "Пошук зупинено",
    "search_cancel_button": "Вихід",
    "search_result_short_name": "Коротка назва",
    "search_result_full_name": "Повна назва",
    "search_status_folder": "Папка",
    "search_status_file": "Файл",
    "search_finished_status": "Пошук завершено",
    "search_no_results": "Файли не знайдено",
    "search_results_count": "результат(ів)",
    "search_query_required": "Введіть текст або регулярний вираз для пошуку.",
    "search_no_folder": "Виберіть допустиму папку пошуку.",
    "search_invalid_regex": "Недійсний регулярний вираз: {error}",
    "search_select_folder_title": "Виберіть папку для пошуку",
    "show_hidden_checkbox": "Показати приховані",
    "name_column": "Назва",
    "type_column": "Тип",
    "size_column": "Розмір",
    "modified_column": "Змінено",
    "preview_select_file": "Виберіть файл для попереднього перегляду.",
    "preview_checkbox_label": "Попередній перегляд",
    "preview_ms_office_checkbox_label": "MS Office",
    "folder_selected": "Вибрано папку:\n{path}",
    "no_preview_available": "Попередній перегляд цього елемента недоступний.",
    "unable_preview_pdf": "Не вдалося переглянути PDF.\n{exc}",
    "unable_preview_file": "Не вдалося переглянути файл.\n{exc}",
    "empty_file": "Файл порожній.",
    "preview_truncated_suffix": "\n\n... попередній перегляд скорочено ...",
    "context_open": "Відкрити",
    "context_rename": "Перейменувати",
    "context_new_folder": "Нова папка",
    "restart_required_title": "Потрібен перезапуск",
    "restart_required_message": "Налаштування мови змінено. Перезапустіть програму, щоб застосувати нову мову.",
    "context_refresh": "Оновити",
    "context_print": "Друк",
    "context_copy": "Копіювати",
    "context_cut": "Вирізати",
    "context_paste": "Вставити",
    "context_remove_to_recycle_bin": "Перемістити до кошика",
    "context_delete": "Видалити",
    "ok_button": "OK",
    "cancel_button": "Скасувати",
    "context_add_to_archive": "Додати до архіву",
    "context_extract_from_archive": "Вилучити з архіву сюди",
    "context_extract_from_archive_here": "Вилучити з архіву сюди",
    "context_extract_from_archive_into": "Вилучити з архіву в",
    "archive_extract_folder_label": "Шлях до папки",
    "archive_extract_select_folder_title": "Виберіть папку призначення",
    "this_pc_root": "Цей комп'ютер",
    "tree_expand_placeholder": "...",
    "page_label": "Сторінка {page_no}/{page_count}",
    "showing_first_pages": "Показано перші {shown_pages} сторінок з {page_count}...",
    "page_move_error_title": "Переміщення сторінки PDF",
    "unable_move_pdf_page": "Не вдалося перемістити сторінку PDF.\n{exc}",
    "drop_overlay_label": "Перетягнути на сторінку {page_index}",
    "preview_edit_button": "Відкрити",
    "preview_save_button": "Зберегти",
    "preview_cancel_button": "Скасувати",
    "preview_save_as_button": "Зберегти як",
    "preview_delete_button": "Видалити файл",
    "preview_zoom_in_button": "Збільшити",
    "preview_zoom_out_button": "Зменшити",
    "preview_show_mode": "Режим перегляду",
    "preview_show_1_page_wide": "1 сторінка по ширині",
    "preview_show_2_pages_wide": "2 сторінки по ширині",
    "preview_show_1_page_tall": "1 сторінка по висоті",
    "preview_show_manual_scale": "Ручний масштаб",
    "preview_rotate_button": "Повернути",
    "preview_rotate_all_left_button": "Повернути все ліворуч",
    "preview_rotate_left_button": "Повернути ліворуч",
    "preview_rotate_right_button": "Повернути праворуч",
    "preview_rotate_all_right_button": "Повернути все праворуч",
    "preview_auto_rotate_button": "Автоматичне обертання",
    "preview_optimize_button": "Оптимізувати",
    "preview_adjust_page_width_button": "Підігнати ширину сторінок",
    "preview_remove_page_button": "Видалити сторінку",
    "preview_move_page_button": "Перемістити сторінку",
    "preview_load_all_button": "Завантажити все",
    "preview_pin_button": "Закріпити вкладку",
    "preview_unpin_button": "Відкріпити вкладку",
    "preview_close_tab_button": "Закрити вкладку",
    "preview_import_button": "Імпортувати",
    "preview_import_from_file_button": "Імпортувати з файлу",

    "preview_import_from_scanner_button": "Імпортувати зі сканера",
    "preview_export_pages_button": "Експортувати сторінки",
    "import_pdf_dialog_title": "Імпорт PDF з файлу",
    "import_pdf_source_label": "Ім'я файлу джерела",
    "import_pdf_browse_button": "Огляд...",
    "import_pdf_file_dialog_title": "Виберіть PDF файл",
    "import_pdf_destination_label": "Призначення",
    "import_pdf_after_page": "Після сторінки",
    "import_pdf_source_required": "Виберіть PDF файл для імпорту.",
    "export_pdf_pages_dialog_title": "Експортувати сторінки",
    "export_pdf_page_numbers_label": "Номери сторінок",
    "export_pdf_file_name_label": "Ім'я файлу",
    "export_pdf_file_name_required": "Введіть ім'я файлу для експорту.",
    "export_pdf_page_numbers_invalid": "Введіть номери сторінок у форматі 1,3-5.",
    "export_pdf_save_dialog_title": "Зберегти експортовані сторінки",
    "move_page_dialog_title": "Перемістити сторінку PDF",
    "move_page_source_label": "Сторінка для переміщення:",
    "move_page_destination_label": "Призначення:",
    "move_page_destination_page_label": "Номер сторінки:",
    "move_page_at_begin": "На початок",
    "move_page_before": "Перед номером",
    "move_page_after": "Після номера",
    "move_page_at_end": "У кінець",
    "scan": "Сканувати",
    "print_dialog_title": "Друк",
    "print_universal_print_label": "Сервіс",
    "print_printer_label": "Принтер",
    "print_copies_label": "Копії",
    "print_range_label": "Діапазон друку",
    "print_range_all": "Все",
    "print_range_selection": "Вибрані сторінки",
    "print_file_label": "Документ",
    "print_button": "Друк",
    "print_parameters_button": "Параметри принтера",
    "print_cancel_button": "Скасувати",
    "print_no_selection": "Виберіть файл для друку.",
    "print_no_printer": "Для Microsoft Universal Print немає доступних принтерів.",
    "print_error_title": "Помилка друку",
    "print_error_unavailable": "Microsoft Universal Print недоступний у цій збірці.",
    "print_status_success": "Завдання друку надіслано до {printer}.",
    "scan_dialog_title": "Сканування документів",
    "scan_scanner_label": "Сканер",
    "scan_default_scanner": "Сканер за замовчуванням",
    "scan_source_label": "Джерело",
    "scan_source_flatbed": "Планшет",
    "scan_source_adf_simplex": "АПД (односторонньо)",
    "scan_source_adf_duplex": "АПД (двосторонньо)",
    "scan_color_mode_label": "Кольоровий режим",
    "scan_color_mode_color": "Кольоровий",
    "scan_color_mode_grayscale": "Відтінки сірого",
    "scan_color_mode_black_white": "Чорно-білий",
    "scan_dpi_label": "Роздільна здатність (DPI)",
    "scan_page_size_label": "Розмір сторінки",
    "scan_page_size_auto": "Авто",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Тип вихідного файлу",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Сканувати кілька сторінок",
    "scan_output_file_label": "Вихідний файл",
    "scan_browse_button": "Огляд...",
    "scan_open_after_label": "Відкрити після сканування",
    "scan_select_output_file_title": "Виберіть вихідний файл",
    "scan_button": "Сканувати",
    "scan_cancel_button": "Скасувати",
    "scan_output_file_required": "Виберіть вихідний файл.",
    "scan_output_folder_not_exists": "Папка для збереження не існує.",
    "scan_not_available_message": "Форму сканування налаштовано. Інтеграція зі сканером поки недоступна в цій збірці.",
    "select_pdf_page": "Спочатку виберіть сторінку.",
    "confirm_remove_page": "Видалити сторінку {page_no}?",
    "confirm_save_selected_file": "Зберегти зміни у вибраному файлі?",
    "confirm_save_before_exit": "Є незбережені зміни у {count} PDF-файлі(ах). Зберегти перед виходом?",
    "confirm_delete": "Видалити {path}?",
    "scan_overwrite_existing_prompt": "Файл вже існує:\n{path}\n\nПерезаписати цей файл?\nВиберіть Ні, щоб зберегти як новий файл із суфіксом '(1)'.",
    "insert_before": "Вставити перед",
    "insert_after": "Вставити після",
    "undo_no_action": "Нічого відміняти",
    "undo_done": "Скасування виконано",
    "undo_title": "Скасувати",
    "file_type_folder": "Папка",
    "file_type_file": "Файл",
    "file_size_unit_kb": "КБ",
    "tree_optimize_all_pdf": "Оптимізувати всі PDF",
    "tree_adjust_page_width_all_pdf": "Підігнати ширину сторінок для всіх PDF",
    "tree_no_folder_selected": "Спочатку виберіть папку в дереві.",
    "tree_no_folder_or_pdf_selected": "Спочатку виберіть папку або PDF файл у дереві.",
    "tree_optimize_all_done": "Оптимізовано: {optimized_count}\nПомилки: {failed_count}",
    "tree_adjust_page_width_all_done": "Підігнано: {adjusted_count}\nПомилки: {failed_count}",
}
