# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_file": "File",
    "menu_navigation": "Navigazione",
    "menu_document": "Documento",
    "menu_help": "Aiuto",
    "menu_about": "Informazioni",
    "menu_file_options": "Opzioni",
    "options_dialog_title": "Opzioni",
    "options_group_main": "Principale",
    "options_group_search": "Ricerca",
    "options_group_optimization": "Ottimizzazione",
    "options_group_preview": "Anteprima",
    "options_group_scan": "Scansione",
    "settings_ui_locale": "Lingua",
    "settings_show_hidden": "Mostra file nascosti",
    "settings_preview_enabled": "Anteprima abilitata",
    "settings_search_form_case_sensitive": "Maiuscole/minuscole",
    "settings_search_form_whole_word": "Parola intera",
    "settings_search_form_word": "Cerca file Word",
    "settings_search_form_excel": "Cerca file Excel",
    "settings_optimize_pdf_image_width": "Larghezza immagine",
    "settings_optimize_pdf_image_quality": "Qualità immagine",
    "settings_optimize_pdf_color_target_dpi": "DPI target colore",
    "settings_optimize_pdf_color_threshold_dpi": "Soglia DPI colore",
    "settings_optimize_pdf_color_compression": "Compressione colore",
    "settings_optimize_pdf_color_quality": "Qualità colore",
    "settings_optimize_pdf_mono_target_dpi": "DPI target mono",
    "settings_optimize_pdf_mono_threshold_dpi": "Soglia DPI mono",
    "settings_optimize_pdf_mono_compression": "Compressione mono",
    "settings_optimize_pdf_compress_only_if_resized": "Comprimi solo se ridimensionato",
    "settings_pdf_show_pages_limit": "Limite pagine PDF",
    "settings_word_show_pages_limit": "Limite pagine Word",
    "settings_excel_show_pages_limit": "Limite pagine Excel",
    "settings_other_show_pages_limit": "Limite pagine altri",
    "settings_scan_file_type_index": "Tipo file scansione",
    "settings_scan_multiple_pages": "Scansiona più pagine",
    "settings_scan_open_after": "Apri dopo la scansione",
    "options_apply_button": "Applica",
    "options_cancel_button": "Annulla",
    "options_value_true": "Vero",
    "options_value_false": "Falso",
    "options_value_empty": "Vuoto",
    "options_quality_low": "Bassa",
    "options_quality_medium": "Media",
    "options_quality_high": "Alta",
    "locale_name_english": "Inglese",
    "locale_name_ukrainian": "Ucraino",
    "locale_name_german": "Tedesco",
    "locale_name_french": "Francese",
    "locale_name_spanish": "Spagnolo",
    "locale_name_italian": "Italiano",
    "locale_name_portuguese_brazilian": "Portoghese (Brasile)",
    "locale_name_japanese": "Giapponese",
    "locale_name_korean": "Coreano",
    "locale_name_chinese_simplified": "Cinese (semplificato)",
    "locale_name_russian": "Russo",
    "back_button": "Indietro",
    "forward_button": "Avanti",
    "exit_button": "Esci",
    "search_hint": "Cerca...",
    "filter_label": "Filtra",
    "search_in_files_button": "Cerca nei file",
    "search_in_files_dialog_title": "Cerca nei file",
    "search_query_label": "Testo o espressione regolare",
    "search_file_mask_label": "Maschera file",
    "search_clear_mask_tooltip": "Cancella maschera",
    "search_case_sensitive_checkbox": "Maiuscole/minuscole",
    "search_whole_word_checkbox": "Parola intera",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "Filtro data",
    "search_pick_date_tooltip": "Scegli data",
    "search_filter_all_dates": "Tutte le date",
    "search_filter_period": "Periodo",
    "search_date_from": "Da",
    "search_date_to": "A",
    "search_size_filter_label": "Filtro dimensione",
    "search_filter_all_sizes": "Tutte le dimensioni",
    "search_filter_size": "Dimensione",
    "search_size_from": "Da",
    "search_size_to": "A",
    "search_folder_label": "Cartella di ricerca",
    "search_browse_button": "Sfoglia...",
    "search_include_subfolders": "Includi sotto-cartelle",
    "search_mode_label": "Modalità di ricerca",
    "search_mode_text": "Testo",
    "search_mode_regex": "Espressione regolare",
    "search_button": "Cerca",
    "search_stop_button": "Stop",
    "pause_button": "Stop",
    "resume_button": "Stop",
    "search_paused_status": "Ricerca interrotta",
    "search_cancel_button": "Esci",
    "search_result_short_name": "Nome breve",
    "search_result_full_name": "Nome completo",
    "search_status_folder": "Cartella",
    "search_status_file": "File",
    "search_finished_status": "La ricerca è terminata",
    "search_no_results": "Nessun file trovato",
    "search_results_count": "risultato(i)",
    "search_query_required": "Inserisci testo o un'espressione regolare.",
    "search_no_folder": "Seleziona una cartella di ricerca valida.",
    "search_invalid_regex": "Espressione regolare non valida: {error}",
    "search_select_folder_title": "Seleziona cartella di ricerca",
    "show_hidden_checkbox": "Mostra nascosti",
    "name_column": "Nome",
    "type_column": "Tipo",
    "size_column": "Dimensione",
    "modified_column": "Modificato",
    "preview_select_file": "Seleziona un file da visualizzare.",
    "preview_checkbox_label": "Anteprima",
    "folder_selected": "Cartella selezionata:\n{path}",
    "no_preview_available": "Nessuna anteprima disponibile per questo elemento.",
    "unable_preview_pdf": "Impossibile visualizzare l'anteprima PDF.\n{exc}",
    "unable_preview_file": "Impossibile visualizzare l'anteprima del file.\n{exc}",
    "empty_file": "Questo file e vuoto.",
    "preview_truncated_suffix": "\n\n... anteprima troncata ...",
    "context_open": "Apri",
    "context_rename": "Rinomina",
    "context_new_folder": "Nuova cartella",
    "context_refresh": "Aggiorna",
    "context_copy": "Copia",
    "context_cut": "Taglia",
    "context_paste": "Incolla",
    "context_delete": "Elimina",
    "context_add_to_archive": "Aggiungi all'archivio",
    "context_extract_from_archive": "Estrai dall'archivio",
    "scan": "Scansiona",
    "scan_dialog_title": "Scansiona documenti",
    "scan_scanner_label": "Scanner",
    "scan_default_scanner": "Scanner predefinito",
    "scan_source_label": "Sorgente",
    "scan_source_flatbed": "Piano",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Duplex)",
    "scan_color_mode_label": "Modalità colore",
    "scan_color_mode_color": "Colore",
    "scan_color_mode_grayscale": "Scala di grigi",
    "scan_color_mode_black_white": "Bianco e nero",
    "scan_dpi_label": "Risoluzione (DPI)",
    "scan_page_size_label": "Formato pagina",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Tipo di output",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Scansiona più pagine",
    "scan_output_file_label": "File di output",
    "scan_browse_button": "Sfoglia...",
    "scan_open_after_label": "Apri dopo la scansione",
    "scan_select_output_file_title": "Seleziona file di output",
    "scan_button": "Scansiona",
    "scan_cancel_button": "Annulla",
    "scan_output_file_required": "Seleziona un file di output.",
    "scan_output_folder_not_exists": "La cartella di output non esiste.",
    "scan_not_available_message": "Il modulo di scansione è configurato. L'integrazione con lo scanner non è ancora disponibile in questa build.",
    "this_pc_root": "Questo PC",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrate le prime {shown_pages} pagine su {page_count}...",
    "page_move_error_title": "Spostamento pagina PDF",
    "unable_move_pdf_page": "Impossibile spostare la pagina PDF.\n{exc}",
    "drop_overlay_label": "Rilascia sulla pagina {page_index}",
    "preview_edit_button": "Apri",
    "preview_save_button": "Salva",
    "preview_cancel_button": "Annulla",
    "preview_save_as_button": "Salva come",
    "preview_delete_button": "Elimina file",
    "preview_zoom_in_button": "Zoom avanti",
    "preview_zoom_out_button": "Zoom indietro",
    "preview_show_mode": "Modalita di visualizzazione",
    "preview_show_1_page_wide": "Mostra 1 pagina in larghezza",
    "preview_show_2_pages_wide": "Mostra 2 pagine in larghezza",
    "preview_show_1_page_tall": "Mostra 1 pagina in altezza",
    "preview_show_manual_scale": "Scala manuale",
    "preview_rotate_button": "Ruota",
    "preview_rotate_all_left_button": "Ruota tutto a sinistra",
    "preview_rotate_left_button": "Ruota a sinistra",
    "preview_rotate_right_button": "Ruota a destra",
    "preview_rotate_all_right_button": "Ruota tutto a destra",
    "preview_auto_rotate_button": "Rotazione automatica",
    "preview_optimize_button": "Ottimizza",
    "preview_adjust_page_width_button": "Adatta larghezza pagina",
    "preview_remove_page_button": "Rimuovi pagina",
    "preview_move_page_button": "Sposta pagina",
    "preview_load_all_button": "Carica tutto",
    "preview_import_button": "Importa",
    "preview_import_from_file_button": "Importa da file",

    "preview_import_from_scanner_button": "Importa da scanner",
    "preview_export_pages_button": "Esporta pagine",
    "import_pdf_dialog_title": "Importa PDF da file",
    "import_pdf_source_label": "Nome file sorgente",
    "import_pdf_browse_button": "Sfoglia...",
    "import_pdf_file_dialog_title": "Seleziona file PDF",
    "import_pdf_destination_label": "Destinazione",
    "import_pdf_after_page": "Dopo la pagina",
    "import_pdf_source_required": "Seleziona un file PDF da importare.",
    "export_pdf_pages_dialog_title": "Esporta pagine",
    "export_pdf_page_numbers_label": "Numeri di pagina",
    "export_pdf_file_name_label": "Nome file",
    "export_pdf_file_name_required": "Inserisci un nome file per l'esportazione.",
    "export_pdf_page_numbers_invalid": "Inserisci numeri di pagina come 1,3-5.",
    "export_pdf_save_dialog_title": "Salva pagine esportate",
    "move_page_dialog_title": "Sposta pagina PDF",
    "move_page_source_label": "Pagina da spostare:",
    "move_page_destination_label": "Destinazione:",
    "move_page_destination_page_label": "Numero pagina:",
    "move_page_at_begin": "All'inizio",
    "move_page_before": "Prima del numero",
    "move_page_after": "Dopo il numero",
    "move_page_at_end": "Alla fine",
    "select_pdf_page": "Seleziona prima una pagina.",
    "confirm_remove_page": "Rimuovere la pagina {page_no}?",
    "confirm_save_selected_file": "Salvare le modifiche al file selezionato?",
    "confirm_save_before_exit": "Sono presenti modifiche non salvate in {count} file PDF. Salvare prima di uscire?",
    "confirm_delete": "Eliminare {path}?",
    "scan_overwrite_existing_prompt": "Il file esiste gia:\n{path}\n\nSovrascrivere questo file?\nScegliere No per salvare come nuovo file con il suffisso '(1)'.",
    "insert_before": "Inserisci prima",
    "insert_after": "Inserisci dopo",
    "undo_no_action": "Niente da annullare",
    "undo_done": "Annullamento riuscito",
    "undo_title": "Annulla",
    "file_type_folder": "Cartella",
    "file_type_file": "File",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Ottimizza tutti i PDF",
    "tree_adjust_page_width_all_pdf": "Adatta larghezza pagina per tutti",
    "tree_no_folder_selected": "Seleziona prima una cartella nell'albero.",
    "tree_no_folder_or_pdf_selected": "Seleziona prima una cartella o un file PDF nell'albero.",
    "tree_optimize_all_done": "Ottimizzati: {optimized_count}\nNon riusciti: {failed_count}",
    "tree_adjust_page_width_all_done": "Adattati: {adjusted_count}\nNon riusciti: {failed_count}",
}
