TRANSLATIONS = {
    "app_title": "Pdf Explorer",
    "back_button": "Indietro",
    "forward_button": "Avanti",
    "exit_button": "Esci",
    "search_hint": "Cerca...",
    "show_hidden_checkbox": "Mostra nascosti",
    "name_column": "Nome",
    "type_column": "Tipo",
    "size_column": "Dimensione",
    "preview_select_file": "Seleziona un file da visualizzare.",
    "folder_selected": "Cartella selezionata:\n{path}",
    "no_preview_available": "Nessuna anteprima disponibile per questo elemento.",
    "unable_preview_pdf": "Impossibile visualizzare l'anteprima PDF.\n{exc}",
    "unable_preview_file": "Impossibile visualizzare l'anteprima del file.\n{exc}",
    "empty_file": "Questo file e vuoto.",
    "preview_truncated_suffix": "\n\n... anteprima troncata ...",
    "context_open": "Apri",
    "context_rename": "Rinomina",
    "context_delete": "Elimina",
    "this_pc_root": "Questo PC",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrate le prime {shown_pages} pagine su {page_count}...",
    "page_move_error_title": "Spostamento pagina PDF",
    "unable_move_pdf_page": "Impossibile spostare la pagina PDF.\n{exc}",
    "drop_overlay_label": "Rilascia sulla pagina {page_index}",
    "preview_edit_button": "Apri",
    "preview_save_button": "Salva",
    "preview_delete_button": "Elimina file",
    "preview_zoom_in_button": "Zoom avanti",
    "preview_zoom_out_button": "Zoom indietro",
    "preview_show_mode": "Modalita di visualizzazione",
    "preview_show_1_page_wide": "Mostra 1 pagina in larghezza",
    "preview_show_2_pages_wide": "Mostra 2 pagine in larghezza",
    "preview_show_1_page_tall": "Mostra 1 pagina in altezza",
    "preview_rotate_button": "Ruota",
    "preview_rotate_all_left_button": "Ruota tutto a sinistra",
    "preview_rotate_left_button": "Ruota a sinistra",
    "preview_rotate_right_button": "Ruota a destra",
    "preview_rotate_all_right_button": "Ruota tutto a destra",
    "preview_optimize_button": "Ottimizza",
    "preview_adjust_page_width_button": "Adatta larghezza pagina",
    "preview_remove_page_button": "Rimuovi pagina",
    "preview_move_page_button": "Sposta pagina",
    "move_page_dialog_title": "Sposta pagina PDF",
    "move_page_source_label": "Pagina da spostare:",
    "move_page_destination_label": "Destinazione:",
    "move_page_destination_page_label": "Numero pagina:",
    "move_page_at_begin": "All'inizio",
    "move_page_before": "Prima del numero",
    "move_page_after": "Dopo il numero",
    "move_page_at_end": "Alla fine",
    "select_pdf_page": "Seleziona prima una pagina.",
    "confirm_remove_page": "Rimuovere la pagina {page_no}?",
    "confirm_save_selected_file": "Salvare le modifiche al file selezionato?",
    "confirm_save_before_exit": "Sono presenti modifiche non salvate in {count} file PDF. Salvare prima di uscire?",
    "confirm_delete": "Eliminare {path}?",
    "insert_before": "Inserisci prima",
    "insert_after": "Inserisci dopo",
    "undo_no_action": "Niente da annullare",
    "undo_done": "Annullamento riuscito",
    "undo_title": "Annulla",
    "file_type_folder": "Cartella",
    "file_type_file": "File",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Ottimizza tutti i PDF",
    "tree_adjust_page_width_all_pdf": "Adatta larghezza pagina per tutti",
    "tree_no_folder_selected": "Seleziona prima una cartella nell'albero.",
    "tree_no_folder_or_pdf_selected": "Seleziona prima una cartella o un file PDF nell'albero.",
    "tree_optimize_all_done": "Ottimizzati: {optimized_count}\nNon riusciti: {failed_count}",
    "tree_adjust_page_width_all_done": "Adattati: {adjusted_count}\nNon riusciti: {failed_count}",
}
