# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "app_title": "Document Explorer",
    "menu_file": "Arquivo",
    "menu_navigation": "Navegação",
    "menu_document": "Documento",
    "menu_help": "Ajuda",
    "menu_app_manual": "Manual do aplicativo",
    "menu_about": "Sobre",
    "menu_file_options": "Opções",
    "options_dialog_title": "Opções",
    "options_group_main": "Principal",
    "options_group_search": "Pesquisa",
    "options_group_optimization": "Otimização",
    "options_group_preview": "Pré-visualização",
    "options_group_scan": "Digitalização",
    "settings_ui_locale": "Idioma",
    "settings_show_hidden": "Mostrar arquivos ocultos",
    "settings_preview_enabled": "Pré-visualização ativada",
    "settings_search_form_case_sensitive": "Diferenciar maiúsculas/minúsculas",
    "settings_search_form_whole_word": "Palavra inteira",
    "settings_search_form_word": "Pesquisar arquivos Word",
    "settings_search_form_excel": "Pesquisar arquivos Excel",
    "settings_optimize_pdf_image_width": "Largura da imagem",
    "settings_optimize_pdf_image_quality": "Qualidade da imagem",
    "settings_optimize_pdf_color_target_dpi": "DPI alvo colorido",
    "settings_optimize_pdf_color_threshold_dpi": "Limite DPI colorido",
    "settings_optimize_pdf_color_compression": "Compressão colorida",
    "settings_optimize_pdf_color_quality": "Qualidade colorida",
    "settings_optimize_pdf_mono_target_dpi": "DPI alvo mono",
    "settings_optimize_pdf_mono_threshold_dpi": "Limite DPI mono",
    "settings_optimize_pdf_mono_compression": "Compressão mono",
    "settings_optimize_pdf_compress_only_if_resized": "Comprimir somente se redimensionado",
    "settings_pdf_show_pages_limit": "Limite de páginas PDF",
    "settings_word_show_pages_limit": "Limite de páginas Word",
    "settings_excel_show_pages_limit": "Limite de páginas Excel",
    "settings_other_show_pages_limit": "Limite de páginas outras",
    "settings_scan_file_type_index": "Tipo de arquivo de digitalização",
    "settings_scan_multiple_pages": "Digitalizar várias páginas",
    "settings_scan_open_after": "Abrir após a digitalização",
    "options_apply_button": "Aplicar",
    "options_cancel_button": "Cancelar",
    "confirm_yes": "Sim",
    "confirm_no": "Não",
    "options_value_true": "Verdadeiro",
    "options_value_false": "Falso",
    "options_value_empty": "Vazio",
    "options_quality_low": "Baixa",
    "options_quality_medium": "Média",
    "options_quality_high": "Alta",
    "locale_name_english": "Inglês",
    "locale_name_ukrainian": "Ucraniano",
    "locale_name_german": "Alemão",
    "locale_name_french": "Francês",
    "locale_name_spanish": "Espanhol",
    "locale_name_italian": "Italiano",
    "locale_name_portuguese_brazilian": "Português (Brasil)",
    "locale_name_japanese": "Japonês",
    "locale_name_korean": "Coreano",
    "locale_name_chinese_simplified": "Chinês (simplificado)",
    "locale_name_russian": "Russo",
    "back_button": "Voltar",
    "forward_button": "Avancar",
    "folder_up_button": "Pasta superior",
    "exit_button": "Sair",
    "search_hint": "Pesquisar...",
    "filter_label": "Filtrar",
    "search_in_files_button": "Pesquisar em arquivos",
    "search_in_files_dialog_title": "Pesquisar em arquivos",
    "search_query_label": "Texto ou expressão regular",
    "search_file_mask_label": "Máscara de arquivo",
    "search_clear_mask_tooltip": "Limpar máscara",
    "search_case_sensitive_checkbox": "Diferenciar maiúsculas/minúsculas",
    "search_whole_word_checkbox": "Palavra inteira",
    "search_word_checkbox": "Word",
    "search_excel_checkbox": "Excel",
    "search_date_filter_label": "Filtro de data",
    "search_pick_date_tooltip": "Escolher data",
    "search_filter_all_dates": "Todas as datas",
    "search_filter_period": "Período",
    "search_date_from": "De",
    "search_date_to": "Até",
    "search_size_filter_label": "Filtro de tamanho",
    "search_filter_all_sizes": "Todos os tamanhos",
    "search_filter_size": "Tamanho",
    "search_size_from": "De",
    "search_size_to": "Até",
    "search_folder_label": "Pasta de pesquisa",
    "search_browse_button": "Procurar...",
    "search_include_subfolders": "Incluir subpastas",
    "search_mode_label": "Modo de pesquisa",
    "search_mode_text": "Texto",
    "search_mode_regex": "Expressão regular",
    "search_button": "Pesquisar",
    "search_stop_button": "Parar",
    "pause_button": "Parar",
    "resume_button": "Parar",
    "search_paused_status": "Pesquisa interrompida",
    "search_cancel_button": "Sair",
    "search_result_short_name": "Nome curto",
    "search_result_full_name": "Nome completo",
    "search_status_folder": "Pasta",
    "search_status_file": "Arquivo",
    "search_finished_status": "A pesquisa foi concluída",
    "search_no_results": "Nenhum arquivo encontrado",
    "search_results_count": "resultado(s)",
    "search_query_required": "Digite um texto ou expressão regular para pesquisar.",
    "search_no_folder": "Selecione uma pasta de pesquisa válida.",
    "search_invalid_regex": "Expressão regular inválida: {error}",
    "search_select_folder_title": "Selecionar pasta de pesquisa",
    "show_hidden_checkbox": "Mostrar ocultos",
    "name_column": "Nome",
    "type_column": "Tipo",
    "size_column": "Tamanho",
    "modified_column": "Modificado",
    "preview_select_file": "Selecione um arquivo para visualizar.",
    "preview_checkbox_label": "Visualização",
    "folder_selected": "Pasta selecionada:\n{path}",
    "no_preview_available": "Nenhuma visualizacao disponivel para este item.",
    "unable_preview_pdf": "Nao foi possivel visualizar o PDF.\n{exc}",
    "unable_preview_file": "Nao foi possivel visualizar o arquivo.\n{exc}",
    "empty_file": "Este arquivo esta vazio.",
    "preview_truncated_suffix": "\n\n... visualizacao truncada ...",
    "context_open": "Abrir",
    "context_rename": "Renomear",
    "context_new_folder": "Nova pasta",
    "restart_required_title": "Reinicialização necessária",
    "restart_required_message": "As configurações de idioma foram alteradas. Reinicie o aplicativo para aplicar o novo idioma.",
    "context_refresh": "Atualizar",
    "context_print": "Imprimir",
    "context_copy": "Copiar",
    "context_cut": "Recortar",
    "context_paste": "Colar",
    "context_remove_to_recycle_bin": "Mover para a Lixeira",
    "context_delete": "Excluir permanentemente",
    "ok_button": "OK",
    "cancel_button": "Cancelar",
    "context_add_to_archive": "Adicionar ao arquivo",
    "context_extract_from_archive": "Extrair do arquivo aqui",
    "context_extract_from_archive_here": "Extrair do arquivo aqui",
    "context_extract_from_archive_into": "Extrair do arquivo em",
    "archive_extract_folder_label": "Caminho da pasta",
    "archive_extract_override": "Sobrescrever",
    "archive_extract_rename": "Renomear",
    "archive_extract_conflict_message": "Os seguintes arquivos já existem em {path}:\n{names}\n\nEscolha como continuar.",
    "archive_extract_select_folder_title": "Selecionar pasta de destino",
    "scan": "Escanear",
    "print_dialog_title": "Imprimir",
    "print_universal_print_label": "Serviço",
    "print_printer_label": "Impressora",
    "print_copies_label": "Cópias",
    "print_range_label": "Intervalo de impressão",
    "print_range_all": "Tudo",
    "print_range_selection": "Páginas selecionadas",
    "print_file_label": "Documento",
    "print_button": "Imprimir",
    "print_parameters_button": "Parâmetros da impressora",
    "print_cancel_button": "Cancelar",
    "print_no_selection": "Selecione um arquivo para imprimir.",
    "print_no_printer": "Nenhuma impressora está disponível para Microsoft Universal Print.",
    "print_error_title": "Erro de impressão",
    "print_error_unavailable": "Microsoft Universal Print não está disponível nesta compilação.",
    "print_status_success": "Trabalho de impressão enviado para {printer}.",
    "scan_dialog_title": "Digitalizar documentos",
    "scan_scanner_label": "Scanner",
    "scan_default_scanner": "Scanner padrão",
    "scan_source_label": "Origem",
    "scan_source_flatbed": "Mesa plana",
    "scan_source_adf_simplex": "ADF (Simplex)",
    "scan_source_adf_duplex": "ADF (Duplex)",
    "scan_color_mode_label": "Modo de cor",
    "scan_color_mode_color": "Colorido",
    "scan_color_mode_grayscale": "Escala de cinza",
    "scan_color_mode_black_white": "Preto e branco",
    "scan_dpi_label": "Resolução (DPI)",
    "scan_page_size_label": "Tamanho da página",
    "scan_page_size_auto": "Auto",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "Tipo de saída",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "Digitalizar várias páginas",
    "scan_output_file_label": "Arquivo de saída",
    "scan_browse_button": "Procurar...",
    "scan_open_after_label": "Abrir após digitalizar",
    "scan_select_output_file_title": "Selecionar arquivo de saída",
    "scan_button": "Digitalizar",
    "scan_cancel_button": "Cancelar",
    "scan_output_file_required": "Selecione um arquivo de saída.",
    "scan_output_folder_not_exists": "A pasta de saída não existe.",
    "scan_not_available_message": "O formulário de digitalização está configurado. A integração com scanner ainda não está disponível nesta versão.",
    "this_pc_root": "Este Computador",
    "tree_expand_placeholder": "...",
    "page_label": "Pagina {page_no}/{page_count}",
    "showing_first_pages": "Mostrando as primeiras {shown_pages} paginas de {page_count}...",
    "page_move_error_title": "Mover pagina PDF",
    "unable_move_pdf_page": "Nao foi possivel mover a pagina PDF.\n{exc}",
    "drop_overlay_label": "Soltar na pagina {page_index}",
    "preview_edit_button": "Abrir",
    "preview_save_button": "Salvar",
    "preview_cancel_button": "Cancelar",
    "preview_save_as_button": "Salvar como",
    "preview_delete_button": "Excluir arquivo",
    "preview_zoom_in_button": "Aumentar zoom",
    "preview_zoom_out_button": "Diminuir zoom",
    "preview_show_mode": "Modo de exibicao",
    "preview_show_1_page_wide": "Mostrar 1 pagina na largura",
    "preview_show_2_pages_wide": "Mostrar 2 paginas na largura",
    "preview_show_1_page_tall": "Mostrar 1 pagina na altura",
    "preview_show_manual_scale": "Escala manual",
    "preview_rotate_button": "Girar",
    "preview_rotate_all_left_button": "Girar tudo para a esquerda",
    "preview_rotate_left_button": "Girar para a esquerda",
    "preview_rotate_right_button": "Girar para a direita",
    "preview_rotate_all_right_button": "Girar tudo para a direita",
    "preview_auto_rotate_button": "Rotação automática",
    "preview_optimize_button": "Otimizar",
    "preview_adjust_page_width_button": "Ajustar largura da pagina",
    "preview_remove_page_button": "Remover pagina",
    "preview_move_page_button": "Mover pagina",
    "preview_load_all_button": "Carregar tudo",
    "preview_pin_button": "Fixar guia",
    "preview_unpin_button": "Desafixar guia",
    "preview_close_tab_button": "Fechar guia",
    "preview_import_button": "Importar",
    "preview_import_from_file_button": "Importar do arquivo",

    "preview_import_from_scanner_button": "Importar do scanner",
    "preview_export_pages_button": "Exportar páginas",
    "import_pdf_dialog_title": "Importar PDF do arquivo",
    "import_pdf_source_label": "Nome do arquivo de origem",
    "import_pdf_browse_button": "Procurar...",
    "import_pdf_file_dialog_title": "Selecionar arquivo PDF",
    "import_pdf_destination_label": "Destino",
    "import_pdf_after_page": "Depois da página",
    "import_pdf_source_required": "Selecione um arquivo PDF para importar.",
    "export_pdf_pages_dialog_title": "Exportar páginas",
    "export_pdf_page_numbers_label": "Números das páginas",
    "export_pdf_file_name_label": "Nome do arquivo",
    "export_pdf_file_name_required": "Informe um nome de arquivo para exportação.",
    "export_pdf_page_numbers_invalid": "Informe números de páginas como 1,3-5.",
    "export_pdf_save_dialog_title": "Salvar páginas exportadas",
    "move_page_dialog_title": "Mover pagina PDF",
    "move_page_source_label": "Pagina a mover:",
    "move_page_destination_label": "Destino:",
    "move_page_destination_page_label": "Numero da pagina:",
    "move_page_at_begin": "No inicio",
    "move_page_before": "Antes do numero",
    "move_page_after": "Depois do numero",
    "move_page_at_end": "No fim",
    "select_pdf_page": "Selecione uma pagina primeiro.",
    "confirm_remove_page": "Remover a pagina {page_no}?",
    "confirm_save_selected_file": "Salvar alteracoes no arquivo selecionado?",
    "confirm_save_before_exit": "Ha alteracoes nao salvas em {count} arquivo(s) PDF. Salvar antes de sair?",
    "confirm_delete": "Excluir {path}?",
    "scan_overwrite_existing_prompt": "O arquivo ja existe:\n{path}\n\nSobrescrever este arquivo?\nEscolha Nao para salvar como um novo arquivo com o sufixo '(1)'.",
    "insert_before": "Inserir antes",
    "insert_after": "Inserir depois",
    "undo_no_action": "Nada para desfazer",
    "undo_done": "Desfazer concluido",
    "undo_title": "Desfazer",
    "file_type_folder": "Pasta",
    "file_type_file": "Arquivo",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "Otimizar todos os PDFs",
    "tree_adjust_page_width_all_pdf": "Ajustar largura da pagina para todos",
    "tree_no_folder_selected": "Selecione primeiro uma pasta na arvore.",
    "tree_no_folder_or_pdf_selected": "Selecione primeiro uma pasta ou um arquivo PDF na arvore.",
    "tree_optimize_all_done": "Otimizados: {optimized_count}\nFalhas: {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustados: {adjusted_count}\nFalhas: {failed_count}",
}
