TRANSLATIONS = {
    "app_title": "Pdf Explorer",
    "back_button": "Retour",
    "forward_button": "Suivant",
    "exit_button": "Quitter",
    "search_hint": "Rechercher...",
    "show_hidden_checkbox": "Afficher les elements caches",
    "name_column": "Nom",
    "type_column": "Type",
    "size_column": "Taille",
    "preview_select_file": "Selectionnez un fichier pour l'apercu.",
    "folder_selected": "Dossier selectionne :\n{path}",
    "no_preview_available": "Aucun apercu disponible pour cet element.",
    "unable_preview_pdf": "Impossible d'afficher l'apercu PDF.\n{exc}",
    "unable_preview_file": "Impossible d'afficher l'apercu du fichier.\n{exc}",
    "empty_file": "Ce fichier est vide.",
    "preview_truncated_suffix": "\n\n... apercu tronque ...",
    "context_open": "Ouvrir",
    "context_rename": "Renommer",
    "context_delete": "Supprimer",
    "this_pc_root": "Ce PC",
    "tree_expand_placeholder": "...",
    "page_label": "Page {page_no}/{page_count}",
    "showing_first_pages": "Affichage des {shown_pages} premieres pages sur {page_count}...",
    "page_move_error_title": "Deplacement de page PDF",
    "unable_move_pdf_page": "Impossible de deplacer la page PDF.\n{exc}",
    "drop_overlay_label": "Deposer sur la page {page_index}",
    "preview_edit_button": "Ouvrir",
    "preview_save_button": "Enregistrer",
    "preview_delete_button": "Supprimer le fichier",
    "preview_zoom_in_button": "Zoom avant",
    "preview_zoom_out_button": "Zoom arriere",
    "preview_rotate_button": "Pivoter",
    "preview_rotate_all_left_button": "Tout pivoter a gauche",
    "preview_rotate_left_button": "Pivoter a gauche",
    "preview_rotate_right_button": "Pivoter a droite",
    "preview_rotate_all_right_button": "Tout pivoter a droite",
    "preview_optimize_button": "Optimiser",
    "preview_ajust_page_width_button": "Ajuster la largeur des pages",
    "preview_remove_page_button": "Supprimer la page",
    "preview_move_page_button": "Deplacer la page",
    "move_page_dialog_title": "Deplacer la page PDF",
    "move_page_source_label": "Page a deplacer:",
    "move_page_destination_label": "Destination:",
    "move_page_destination_page_label": "Numero de page:",
    "move_page_at_begin": "Au debut",
    "move_page_before": "Avant le numero",
    "move_page_after": "Apres le numero",
    "move_page_at_end": "A la fin",
    "select_pdf_page": "Selectionnez d'abord une page.",
    "confirm_remove_page": "Supprimer la page {page_no} ?",
    "confirm_save_selected_file": "Enregistrer les modifications du fichier selectionne ?",
    "confirm_save_before_exit": "Vous avez des modifications non enregistrees dans {count} fichier(s) PDF. Enregistrer avant de quitter ?",
    "confirm_delete": "Supprimer {path} ?",
    "insert_before": "Inserer avant",
    "insert_after": "Inserer apres",
    "undo_no_action": "Rien a annuler",
    "undo_done": "Annulation reussie",
    "undo_title": "Annuler",
    "file_type_folder": "Dossier",
    "file_type_file": "Fichier",
    "file_size_unit_kb": "Ko",
    "tree_optimize_all_pdf": "Optimiser tous les PDF",
    "tree_adjust_page_width_all_pdf": "Ajuster la largeur des pages pour tous",
    "tree_no_folder_selected": "Selectionnez d'abord un dossier dans l'arborescence.",
    "tree_no_folder_or_pdf_selected": "Selectionnez d'abord un dossier ou un fichier PDF dans l'arborescence.",
    "tree_optimize_all_done": "Optimises : {optimized_count}\nEchecs : {failed_count}",
    "tree_adjust_page_width_all_done": "Ajustes : {adjusted_count}\nEchecs : {failed_count}",
}
