TRANSLATIONS = {
    "app_title": "Pdf Explorer",
    "back_button": "戻る",
    "forward_button": "進む",
    "exit_button": "終了",
    "search_hint": "検索...",
    "show_hidden_checkbox": "隠しファイルを表示",
    "name_column": "名前",
    "type_column": "種類",
    "size_column": "サイズ",
    "preview_select_file": "プレビューするファイルを選択してください。",
    "folder_selected": "選択したフォルダー:\n{path}",
    "no_preview_available": "この項目のプレビューは利用できません。",
    "unable_preview_pdf": "PDF をプレビューできません。\n{exc}",
    "unable_preview_file": "ファイルをプレビューできません。\n{exc}",
    "empty_file": "このファイルは空です。",
    "preview_truncated_suffix": "\n\n... プレビューは省略されました ...",
    "context_open": "開く",
    "context_rename": "名前変更",
    "context_delete": "削除",
    "scan": "スキャン",
    "scan_dialog_title": "ドキュメントをスキャン",
    "scan_scanner_label": "スキャナー",
    "scan_default_scanner": "既定のスキャナー",
    "scan_source_label": "ソース",
    "scan_source_flatbed": "フラットベッド",
    "scan_source_adf_simplex": "ADF（片面）",
    "scan_source_adf_duplex": "ADF（両面）",
    "scan_color_mode_label": "カラーモード",
    "scan_color_mode_color": "カラー",
    "scan_color_mode_grayscale": "グレースケール",
    "scan_color_mode_black_white": "白黒",
    "scan_dpi_label": "解像度 (DPI)",
    "scan_page_size_label": "ページサイズ",
    "scan_page_size_auto": "自動",
    "scan_page_size_a4": "A4",
    "scan_page_size_letter": "Letter",
    "scan_page_size_legal": "Legal",
    "scan_output_type_label": "出力タイプ",
    "scan_output_type_pdf": "PDF",
    "scan_output_type_jpeg": "JPEG",
    "scan_multiple_pages_label": "複数ページをスキャン",
    "scan_output_file_label": "出力ファイル",
    "scan_browse_button": "参照...",
    "scan_open_after_label": "スキャン後に開く",
    "scan_select_output_file_title": "出力ファイルを選択",
    "scan_button": "スキャン",
    "scan_cancel_button": "キャンセル",
    "scan_output_file_required": "出力ファイルを選択してください。",
    "scan_output_folder_not_exists": "出力フォルダーが存在しません。",
    "scan_not_available_message": "スキャンフォームは設定されました。このビルドではスキャナー連携はまだ利用できません。",
    "this_pc_root": "この PC",
    "tree_expand_placeholder": "...",
    "page_label": "ページ {page_no}/{page_count}",
    "showing_first_pages": "{page_count} ページ中、先頭 {shown_pages} ページを表示しています...",
    "page_move_error_title": "PDF ページ移動",
    "unable_move_pdf_page": "PDF ページを移動できません。\n{exc}",
    "drop_overlay_label": "ページ {page_index} にドロップ",
    "preview_edit_button": "開く",
    "preview_save_button": "保存",
    "preview_cancel_button": "キャンセル",
    "preview_save_as_button": "名前を付けて保存",
    "preview_delete_button": "ファイルを削除",
    "preview_zoom_in_button": "拡大",
    "preview_zoom_out_button": "縮小",
    "preview_show_mode": "表示モード",
    "preview_show_1_page_wide": "横に1ページ表示",
    "preview_show_2_pages_wide": "横に2ページ表示",
    "preview_show_1_page_tall": "縦に1ページ表示",
    "preview_show_manual_scale": "手動スケール",
    "preview_rotate_button": "回転",
    "preview_rotate_all_left_button": "すべて左回転",
    "preview_rotate_left_button": "左回転",
    "preview_rotate_right_button": "右回転",
    "preview_rotate_all_right_button": "すべて右回転",
    "preview_auto_rotate_button": "自動回転",
    "preview_optimize_button": "最適化",
    "preview_adjust_page_width_button": "ページ幅を調整",
    "preview_remove_page_button": "ページを削除",
    "preview_move_page_button": "ページを移動",
    "preview_import_from_file_button": "ファイルからインポート",
    "preview_export_pages_button": "ページをエクスポート",
    "import_pdf_dialog_title": "ファイルからPDFをインポート",
    "import_pdf_source_label": "元ファイル名",
    "import_pdf_browse_button": "参照...",
    "import_pdf_file_dialog_title": "PDFファイルを選択",
    "import_pdf_destination_label": "挿入先",
    "import_pdf_after_page": "ページの後",
    "import_pdf_source_required": "インポートするPDFファイルを選択してください。",
    "export_pdf_pages_dialog_title": "ページをエクスポート",
    "export_pdf_page_numbers_label": "ページ番号",
    "export_pdf_file_name_label": "ファイル名",
    "export_pdf_file_name_required": "エクスポートするファイル名を入力してください。",
    "export_pdf_page_numbers_invalid": "1,3-5 のようにページ番号を入力してください。",
    "export_pdf_save_dialog_title": "エクスポートしたページを保存",
    "move_page_dialog_title": "PDFページを移動",
    "move_page_source_label": "移動するページ:",
    "move_page_destination_label": "移動先:",
    "move_page_destination_page_label": "ページ番号:",
    "move_page_at_begin": "先頭へ",
    "move_page_before": "番号の前",
    "move_page_after": "番号の後",
    "move_page_at_end": "末尾へ",
    "select_pdf_page": "先にページを選択してください。",
    "confirm_remove_page": "ページ {page_no} を削除しますか?",
    "confirm_save_selected_file": "選択したファイルへの変更を保存しますか?",
    "confirm_save_before_exit": "{count} 個の PDF ファイルに未保存の変更があります。終了前に保存しますか?",
    "confirm_delete": "{path} を削除しますか?",
    "insert_before": "前に挿入",
    "insert_after": "後に挿入",
    "undo_no_action": "元に戻す操作はありません",
    "undo_done": "元に戻しました",
    "undo_title": "元に戻す",
    "file_type_folder": "フォルダー",
    "file_type_file": "ファイル",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "すべての PDF を最適化",
    "tree_adjust_page_width_all_pdf": "すべてのページ幅を調整",
    "tree_no_folder_selected": "先にツリーでフォルダーを選択してください。",
    "tree_no_folder_or_pdf_selected": "先にツリーでフォルダーまたは PDF ファイルを選択してください。",
    "tree_optimize_all_done": "最適化: {optimized_count}\n失敗: {failed_count}",
    "tree_adjust_page_width_all_done": "調整: {adjusted_count}\n失敗: {failed_count}",
}
