TRANSLATIONS = {
    "app_title": "Pdf Провідник",
    "back_button": "Назад",
    "forward_button": "Вперед",
    "exit_button": "Вихід",
    "search_hint": "Пошук...",
    "show_hidden_checkbox": "Показати приховані",
    "name_column": "Назва",
    "type_column": "Тип",
    "size_column": "Розмір",
    "preview_select_file": "Виберіть файл для попереднього перегляду.",
    "folder_selected": "Вибрано папку:\n{path}",
    "no_preview_available": "Попередній перегляд цього елемента недоступний.",
    "unable_preview_pdf": "Не вдалося переглянути PDF.\n{exc}",
    "unable_preview_file": "Не вдалося переглянути файл.\n{exc}",
    "empty_file": "Файл порожній.",
    "preview_truncated_suffix": "\n\n... попередній перегляд скорочено ...",
    "context_open": "Відкрити",
    "context_rename": "Перейменувати",
    "context_delete": "Видалити",
    "this_pc_root": "Цей комп'ютер",
    "tree_expand_placeholder": "...",
    "page_label": "Сторінка {page_no}/{page_count}",
    "showing_first_pages": "Показано перші {shown_pages} сторінок з {page_count}...",
    "page_move_error_title": "Переміщення сторінки PDF",
    "unable_move_pdf_page": "Не вдалося перемістити сторінку PDF.\n{exc}",
    "drop_overlay_label": "Перетягнути на сторінку {page_index}",
    "preview_edit_button": "Відкрити",
    "preview_save_button": "Зберегти",
    "preview_delete_button": "Видалити файл",
    "preview_zoom_in_button": "Збільшити",
    "preview_zoom_out_button": "Зменшити",
    "preview_show_mode": "Режим перегляду",
    "preview_show_1_page_wide": "1 сторінка по ширині",
    "preview_show_2_pages_wide": "2 сторінки по ширині",
    "preview_show_1_page_tall": "1 сторінка по висоті",
    "preview_rotate_button": "Повернути",
    "preview_rotate_all_left_button": "Повернути все ліворуч",
    "preview_rotate_left_button": "Повернути ліворуч",
    "preview_rotate_right_button": "Повернути праворуч",
    "preview_rotate_all_right_button": "Повернути все праворуч",
    "preview_optimize_button": "Оптимізувати",
    "preview_adjust_page_width_button": "Підігнати ширину сторінок",
    "preview_remove_page_button": "Видалити сторінку",
    "preview_move_page_button": "Перемістити сторінку",
    "move_page_dialog_title": "Перемістити сторінку PDF",
    "move_page_source_label": "Сторінка для переміщення:",
    "move_page_destination_label": "Призначення:",
    "move_page_destination_page_label": "Номер сторінки:",
    "move_page_at_begin": "На початок",
    "move_page_before": "Перед номером",
    "move_page_after": "Після номера",
    "move_page_at_end": "У кінець",
    "select_pdf_page": "Спочатку виберіть сторінку.",
    "confirm_remove_page": "Видалити сторінку {page_no}?",
    "confirm_save_selected_file": "Зберегти зміни у вибраному файлі?",
    "confirm_save_before_exit": "Є незбережені зміни у {count} PDF-файлі(ах). Зберегти перед виходом?",
    "confirm_delete": "Видалити {path}?",
    "insert_before": "Вставити перед",
    "insert_after": "Вставити після",
    "undo_no_action": "Нічого відміняти",
    "undo_done": "Скасування виконано",
    "undo_title": "Скасувати",
    "file_type_folder": "Папка",
    "file_type_file": "Файл",
    "file_size_unit_kb": "КБ",
    "tree_optimize_all_pdf": "Оптимізувати всі PDF",
    "tree_adjust_page_width_all_pdf": "Підігнати ширину сторінок для всіх PDF",
    "tree_no_folder_selected": "Спочатку виберіть папку в дереві.",
    "tree_no_folder_or_pdf_selected": "Спочатку виберіть папку або PDF файл у дереві.",
    "tree_optimize_all_done": "Оптимізовано: {optimized_count}\nПомилки: {failed_count}",
    "tree_adjust_page_width_all_done": "Підігнано: {adjusted_count}\nПомилки: {failed_count}",
}
