TRANSLATIONS = {
    "app_title": "Pdf Explorer",
    "back_button": "后退",
    "forward_button": "前进",
    "exit_button": "退出",
    "search_hint": "搜索...",
    "show_hidden_checkbox": "显示隐藏项",
    "name_column": "名称",
    "type_column": "类型",
    "size_column": "大小",
    "preview_select_file": "请选择要预览的文件。",
    "folder_selected": "已选择文件夹:\n{path}",
    "no_preview_available": "此项目没有可用预览。",
    "unable_preview_pdf": "无法预览 PDF。\n{exc}",
    "unable_preview_file": "无法预览文件。\n{exc}",
    "empty_file": "该文件为空。",
    "preview_truncated_suffix": "\n\n... 预览已截断 ...",
    "context_open": "打开",
    "context_rename": "重命名",
    "context_delete": "删除",
    "scan": "扫描",
    "this_pc_root": "此电脑",
    "tree_expand_placeholder": "...",
    "page_label": "第 {page_no}/{page_count} 页",
    "showing_first_pages": "正在显示前 {shown_pages} 页，共 {page_count} 页...",
    "page_move_error_title": "PDF 页面移动",
    "unable_move_pdf_page": "无法移动 PDF 页面。\n{exc}",
    "drop_overlay_label": "拖放到第 {page_index} 页",
    "preview_edit_button": "打开",
    "preview_save_button": "保存",
    "preview_save_as_button": "另存为",
    "preview_delete_button": "删除文件",
    "preview_zoom_in_button": "放大",
    "preview_zoom_out_button": "缩小",
    "preview_show_mode": "显示模式",
    "preview_show_1_page_wide": "按宽度显示 1 页",
    "preview_show_2_pages_wide": "按宽度显示 2 页",
    "preview_show_1_page_tall": "按高度显示 1 页",
    "preview_show_manual_scale": "手动缩放",
    "preview_rotate_button": "旋转",
    "preview_rotate_all_left_button": "全部向左旋转",
    "preview_rotate_left_button": "向左旋转",
    "preview_rotate_right_button": "向右旋转",
    "preview_rotate_all_right_button": "全部向右旋转",
    "preview_auto_rotate_button": "自动旋转",
    "preview_optimize_button": "优化",
    "preview_adjust_page_width_button": "调整页面宽度",
    "preview_remove_page_button": "删除页面",
    "preview_move_page_button": "移动页面",
    "move_page_dialog_title": "移动 PDF 页面",
    "move_page_source_label": "要移动的页面:",
    "move_page_destination_label": "目标位置:",
    "move_page_destination_page_label": "页码:",
    "move_page_at_begin": "到开头",
    "move_page_before": "在该页码之前",
    "move_page_after": "在该页码之后",
    "move_page_at_end": "到末尾",
    "select_pdf_page": "请先选择页面。",
    "confirm_remove_page": "删除第 {page_no} 页吗?",
    "confirm_save_selected_file": "保存所选文件的更改吗?",
    "confirm_save_before_exit": "有 {count} 个 PDF 文件包含未保存更改。退出前是否保存?",
    "confirm_delete": "删除 {path} 吗?",
    "insert_before": "在前面插入",
    "insert_after": "在后面插入",
    "undo_no_action": "没有可撤销的操作",
    "undo_done": "撤销成功",
    "undo_title": "撤销",
    "file_type_folder": "文件夹",
    "file_type_file": "文件",
    "file_size_unit_kb": "KB",
    "tree_optimize_all_pdf": "优化所有 PDF",
    "tree_adjust_page_width_all_pdf": "调整所有页面宽度",
    "tree_no_folder_selected": "请先在树中选择文件夹。",
    "tree_no_folder_or_pdf_selected": "请先在树中选择文件夹或 PDF 文件。",
    "tree_optimize_all_done": "已优化: {optimized_count}\n失败: {failed_count}",
    "tree_adjust_page_width_all_done": "已调整: {adjusted_count}\n失败: {failed_count}",
}
